### ISSUE TITLE
Building test classes failed in devel branch (OpenMP disabled)

### ISSUE THREAD

**Issue by laurensdv** [rdfhdt/hdt-cpp#10]
ilterSearch.cpp:(.text.startup+0x70c): undefined reference to `typeinfo for hdt::LiteralDictionary'
filterSearch.cpp:(.text.startup+0x75b): undefined reference to`hdt::LiteralDictionary::substringToId(unsigned char_, unsigned int, unsigned int__)'
collect2: error: ld returned 1 exit status
Makefile:89: recipe for target 'tests/filterSearch' failed
make: *_\* [tests/filterSearch] Error 1

**Comment by mielvds** [comment]
@laurensdv is this still an issue?

**Comment by RubenVerborgh** [comment]
The tests build, and this is tested on Travis.
