### ISSUE TITLE
Unable to create an HDT file based on README instructions

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#104]
Thanks for updating the README file on the develop branch.

Small suggestion: maybe indicate in `README.md` that the `tools` directory is inside the `libhdt` directory.  (This saves new users a `find` command.)

When I run the documented steps I get the following:

```sh
$ ./autogen.sh 
$ ./configure
$ make -j2
$ libhdt/tools/rdf2hdt <FROM> <TO>
<PREFIX>/hdt-cpp/libhdt/tools/.libs/lt-rdf2hdt: error while loading shared libraries: ../.libs/libhdt.so: cannot open shared object file: No such file or directory
```

**Comment by ptorrestr** [comment]
Hi,  I'm not able to reproduce this error. 

It looks like `libhdt.so` was not build. After doing `make` you will have a folder in `libhdt/.libs` with the shared library. If the shared library is not present, then the references from the objects in `libhdt/tools/.libs` will fail

**Comment by wouterbeek** [comment]
@ptorrestr This time it does work.  I'm not sure why it is different now :(  Closing this issue anyway...

**Comment by LaurensRietveld** [comment]
Did you by any chance move the directory? There is an absolute reference to
the lib file created while compiling, and that breaks if the hdt-cpp
directory is moved or renamed
