### ISSUE TITLE
Unable to query literals with escaped double quotes

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#105]
When a literal's lexical form contains escaped double quotes, this literal cannot be queried in a standards-compliant way.  Let's take the following example data:

```ttl
<x:x> <y:y> "\""^^<z:z>
```

For the HDT file that is generated based on the above data, query [1] does not return this particular triple, but query [2] does.  The problem is that [1] is the standard-compliant notation (double quotes must be escaped in N-Triples 1.1 lexical forms), and is how literals are returned by standards-compliant tools.

```
[1] ? ? "\""^^<z:z>
[2] ? ? """^^<z:z>
```

The current workaround is to go through the object term prior to each HDT query, in order to replace all escaped double quotes with unescaped ones.

It would be better if the HDT file would either store escaped quotes in a standards-compliant way, or -- in case solution (1) is not feasible -- it would be better if the HDT library would perform the unescaping of escaped double quotes (as described in the workaround).

PS: The issue also appears in Linked Data Fragments APIs: [example](http://fragments.dbpedia.org/2014/en?object=%22%22Eagle%20Keepers%22%22%40en).

**Comment by RubenVerborgh** [comment]
HDT is not N-Triples nor Turtle. The internal syntax for this is `"""^^<z:z>`, i.e., a literal is represented by its (unescaped) value, surrounded by `""` and possibly appending a type/language. So not a bug, but a feature. In order to translate this into N-Triples, a serializer is needed.

The TPF API is behaving [as expected](https://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#controls):

> constant text literal: the text value of the literal, surrounded by double quotes ", e.g., "my text"

**Comment by RubenVerborgh** [comment]
Reason for this is that a literal can be represented in multiple ways with escapes, whereas exactly 1 HDT representation of each literal exists.

**Comment by wouterbeek** [comment]
Thanks for the info!  I was not aware of the difference between HDT
and N-Triples.  Is this documented somewhere?

I do not follow your reasoning WRT canonicity though.  The fact that
*a* canonical form is beneficial does not imply that this canonical
form must or must not comply with N-Triples?  (I would argue that
having a canonical form that is also N-Triples has benefits over a
canonical form that looks a lot like N-Triples but deviates from it in
subtle ways.)

From an implementation point of view, it is more difficult to parse
the custom HDT format than it is to parse N-Triples.  Specifically, in
order to parse literals in the custom HDT format the parser must look
ahead for the last double quote character.  Even if the sequence `"<`
is encountered, the parser must still look further ahead, because this
sequence is allowed to appear within a lexical form.  In N-Triples the
parser observes either a double quote that is directly preceded by a
backslash (`\"`, i.e., the double quote is content), or a double quote
that is not directly preceded by a backslash (i.e., the double quote
is not part of the content but belongs to the serialization syntax).
IOW, parsing HDT literals requires a window that has the size of the
(potentially lengthy) literal.  Parsing N-Triples literals requires a
window of size 2, regardless of the size of the literal.

PS: What does "text value" mean in the TPF documentation?  I have not
seen that terminology in Linked Data before.  Is it equivalent to the
notion of lexical form?

**Comment by RubenVerborgh** [comment]
> Thanks for the info! I was not aware of the difference between HDT
and N-Triples. Is this documented somewhere?

Not sure, I just figured this out from existing HDT files, and it happened to be compatible with the [N3.js internal representation](https://github.com/RubenVerborgh/N3.js#triple-representation) (minus angular brackets around types).

> I do not follow your reasoning WRT canonicity though. The fact that
a canonical form is beneficial does not imply that this canonical
form must or must not comply with N-Triples?

True, but why should it comply with N-Triples in the first place?
There are many different RDF syntaxes.
HDT simply does not need the escaping; HDT is storage and solves a different problem than N-Triples, where the escaping makes sense.

> From an implementation point of view, it is more difficult to parse
the custom HDT format than it is to parse N-Triples.

It's the opposite. HDT format: just remove the `"`.
N-Triples: remove and replace escapes.

> the parser must look
ahead for the last double quote character.

No, you can run back from the last character, and the first quote you encounter is the delimiter.

> Parsing N-Triples literals requires a
window of size 2, regardless of the size of the literal.

Yes, but you have to do search and replace still, and create a new string.
With HDT, the textual value is a substring of the HDT value; no need to copy.

> PS: What does "text value" mean in the TPF documentation? I have not
seen that terminology in Linked Data before. Is it equivalent to the
notion of lexical form?

Yes, It should be "lexical form".

**Comment by RubenVerborgh** [comment]
Put differently: if your use case is reading HDT and serializing N-Triples, yes, it would be beneficial to have the escapes in there. But if your use case is _using_ the RDF that comes from an HDT file in memory, then the escapes serve no good purpose.

**Comment by wouterbeek** [comment]
Thanks again for the info!  We seem to agree that the window for parsing HDT literals is the length of the literal (this is what you call "running back from the last character"), but we seem to disagree on whether such a long window makes parsing easier or more difficult :-P
