### ISSUE TITLE
rdf2hdt of .gz file 

### ISSUE THREAD

**Issue by D063520** [rdfhdt/hdt-cpp#109]
Hello, 

I'm using rdf2hdt to create .hdt files from .nt files and it works great. I now had a file in .nt.gz format and, as far as I understood, the tool should be able to uncompress the file on the flight. Unfortunately it is not working. I tried without any option, something like:

rdf2hdt test.nt.gz out.hdt

Do I do something wrong?

Thank you

**Comment by mielvds** [comment]
At the moment, this is not yet possible. We are looking for a piping solution. Please see https://github.com/rdfhdt/hdt-cpp/issues/47

**Comment by D063520** [comment]
Hello, I would suggest then to change the README. I lost a lot of time to recompile and trying to making it work.

**Comment by mielvds** [comment]
I might be wrong after all... Check out https://github.com/rdfhdt/hdt-cpp/pull/61 & https://github.com/rdfhdt/hdt-cpp/issues/82

**Comment by wouterbeek** [comment]
@mielvds I'm also under the impression that this is implemented, but that n00bs like myself simple lack the Bash fu to invoke this feature correctly.  A working example in README would help us a lot.
