### ISSUE TITLE
SPARQL

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#111]
Is it possible to run SPARQL queries against a HDT file?

**Comment by mielvds** [comment]
It is, but only running Java + hdt-java + hdt-jena: https://github.com/rdfhdt/hdt-java
You probably need to generate the HDT file with java too; both libraries might no longer be compatible.

You can also publish the HDT with a TPF server (https://github.com/LinkedDataFragments/Server.js) and query it with SPARQL using a TPF client (https://github.com/LinkedDataFragments/Client.js).
