### ISSUE TITLE
Can hdt-cpp parse JSON?

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#124]
I've found JSON in [the RDFNotation definition](https://github.com/rdfhdt/hdt-cpp/blob/e44f6b3487042022aa33e883685f65c3d809d760/hdt-lib/include/HDTEnums.hpp#L141) but not in the help message of rdf2hdt. So I was wondering if it's just a placeholder or if hdt-cpp can parse JSON.

**Comment by LaurensRietveld** [comment]
It's just a placeholder. Parsing JSON is not possible atm (and will probably only be possible if serd starts supporting json)

**Comment by drobilla** [comment]
I would like to add JSON-LD support to serd, but it's quite a complicated spec compared to Turtle and friends, so no idea when I'll be able to get around to actually doing so.
