### ISSUE TITLE
HDT memory load

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#132]
When I use Fuseki on top of HDT, and then I query Fuseki with some SELECT query... is the HDT file loaded entirely into memory? So, for example, if my HDT file 30GB, do I need 30GB of RAM to load it all?

**Comment by MarioAriasGa** [comment]
No, Fuseki uses mapIndexed() which uses mmap, the OS will handle the paging of memory blocks from disk to memory.
