### ISSUE TITLE
Compiling errors on CentOS7

### ISSUE THREAD

**Issue by gatemezing** [rdfhdt/hdt-cpp#133]
Hi guys, 
I've just started  to use this nice tool but I am struggling to compile on a CentOS7 server. 
I am still getting this  error `/usr/local/lib: file not recognized: Is a directory` (see screenshot below) 
https://www.dropbox.com/s/50dper8mbkt640n/Capture%20d%27%C3%A9cran%202017-11-01%2020.42.24.png?dl=0 
Sorry if this issue has been raised before. TIA

**Comment by r4t56ytyhgty** [comment]
Did you try this?

```
$ ./autogen.sh
$ ./configure LIBS="-I /usr/local/include -L/usr/local/lib"
$ make
```

Any luck? Or still getting the error?

**Comment by gatemezing** [comment]
Hi @r4t56ytyhgty, thanks for the tip. 
Yesterday I tried it by doing this `./autogen.sh && ./configure LIBS="-I /usr/local/include -L/usr/local/lib"  && make` .
I'll tried again and let you know.

**Comment by gatemezing** [comment]
Well, seems to be working now 👍 
Now I solved one issue (again) related to the libs for SERD by adjusting the 
`PKG_CONFIG_PATH` and after running the previous command it compiles. I can close the issue.
