### ISSUE TITLE
Fuseki config: specify index

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#134]
When I use HDT with Fuseki, [the documentation](http://www.rdfhdt.org/manual-of-hdt-integration-with-jena/) says to configure HDT like this:

```
<#graph1> rdfs:label "RDF Graph1 from HDT file" ;
        rdf:type hdt:HDTGraph ;
        hdt:fileName "file1.hdt".
```

I was wondering if I have to also specify the path to the `.hdt.index` file? Or if the index is used automatically even if I don't specify it in the config?

**Comment by LaurensRietveld** [comment]
Tbh, no clue. This seems like something that you should ask in the java repo: https://github.com/rdfhdt/hdt-java
