### ISSUE TITLE
rdf2hdt can't handle more than 4 billions triples

### ISSUE THREAD

**Issue by Arkanosis** [rdfhdt/hdt-cpp#135]
Hello,

I'm trying to get an hdt file from the [Wikidata turtle dump](https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.ttl.gz) of the 1st of November 2017 using the current HEAD revision of rdf2hdt (7d92f3f13019a82f35ac88b8011277fddae90270).

Everything looked okay until the “Removing duplicate triples” step which goes from 0 % progress to ~95 % progress (~91 % to ~94 % progress overall, respectively) and then starts over. It started after roughly 20 hours of runtime; it has been running for almost 37 hours now, that is around 17 hours “Removing duplicate triples”.

I've lost all hope having the conversion finish, but if I can give you useful information from the still running process before I kill it (it's eating ~200 GiB RAM, I can't let it run indefinitely), please let me know.

**Comment by Arkanosis** [comment]
I got it: rdf2hdt does not handle more than 2<sup>32</sup> triples (because it uses `unsigned int`s as indexes) and Wikidata has now more than 4 billion triples, making the `TriplesList::removeDuplicates`' index overflow.

This index is quite easy to fix by using `std::vector<TripleID>::size_type` instead of `unsigned int` as index type, but I'm afraid that 32 bits indexes are used in other places where they don't cause a crash but generate wrong results :-/

**Comment by akuckartz** [comment]
:+1: for fixing this.

**Comment by sharpaper** [comment]
I wonder why HDT was not designed to handle large datasets from the beginning (aka streaming content), considering that compressing large dataset is where this tool shines.
On the same note, being able to handle large datasets is the only option that will help spread HDT as a format.

**Comment by wouterbeek** [comment]
@Arkanosis Take a look at `develop-64` and the recent LOD-a-lot paper (https://link-springer-com.vu-nl.idm.oclc.org/chapter/10.1007/978-3-319-68204-4_7).

**Comment by sharpaper** [comment]
@wouterbeek The paper is not accessible. Yay for open data :)

**Comment by sharpaper** [comment]
If [this](http://lod-a-lot.lod.labs.vu.nl/about/) is the same project... LOD-a-lot is a single HDT file with more than 28 billion unique, using 16GB of RAM? How did you manage to build a single HDT with 28 billion triples? I can't even imagine how much RAM the conversion process consumed!

**Comment by mielvds** [comment]
here's your open data: https://aic.ai.wu.ac.at/qadlod/lodalot/iswc2017/

**Comment by v4ss4llo** [comment]
Is this issue supposed to be fixed by the `develop-64` branch in the source?

**Comment by Arkanosis** [comment]
I haven't had the time to check yet, but given @wouterbeek [has managed](https://lists.wikimedia.org/pipermail/wikidata/2017-December/011588.html) to build a hdt file for Wikidata using this branch, I assume that yes.

**Comment by wouterbeek** [comment]
@Arkanosis I can confirm this, `develop-64` was used to create the Wikidata file.

**Comment by wouterbeek** [comment]
64-bit support has now been added to the `develop` branch.
