### ISSUE TITLE
Update Wikidata HDT on the website

### ISSUE THREAD

**Issue by v4ss4llo** [rdfhdt/hdt-cpp#139]
I noticed that the [wikidata HDT file on the website](http://www.rdfhdt.org/datasets/) is 1 year old. Would it be possible, please, to make a new updated version of this file using [the latest dump](https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.ttl.bz2)?

**Comment by webdata** [comment]
Yes, I'm working on it, hope to have it soon.

**Comment by v4ss4llo** [comment]
Thank you! Since you're at it, can you please also generate the `.hdt.index`?

**Comment by v4ss4llo** [comment]
It would also be interesting to know some statistics about the conversion...

- how long it took, approximately
- how much RAM it took
- what is the hardware you're running the conversion on (mobo, cpu, ram, disks)

**Comment by v4ss4llo** [comment]
Looking at [this issue](https://github.com/rdfhdt/hdt-cpp/issues/135), I hope rdf2hdt can handle the dump...

**Comment by v4ss4llo** [comment]
Hi @webdata any good luck so far, or errors??

**Comment by wouterbeek** [comment]
@webdata Hi Javier, we already created a Wikidata HDT on 7 Nov, but I forgot to share the links on the Wikidata mailinglist.  (I will do that in a minute.)

The download links are:
  - http://lod-a-lot.lod.labs.vu.nl/data/wikidata.hdt (~45GB)
  - http://lod-a-lot.lod.labs.vu.nl/data/wikidata.hdt.index.v1-1 (~28GB)

**Comment by v4ss4llo** [comment]
Thanks a lot @wouterbeek 
I'll leave this open since the website has not been updated yet.

**Comment by LaurensRietveld** [comment]
Think this issue is more suitable for this repo: https://github.com/rdfhdt/rdfhdt.org . Feel free to open up a ticket there

**Comment by webdata** [comment]
Hi, just to let you know, we have created a new version of wikidata as of 11S 2018: http://www.rdfhdt.org/datasets/

**Comment by danbri** [comment]
has anyone here made interesting use of the wikidata HDT files?
