### ISSUE TITLE
How to install HDT tools system-wide

### ISSUE THREAD

**Issue by v4ss4llo** [rdfhdt/hdt-cpp#140]
`make install` will install the tools in `/usr/local/bin` and the libraries in `/usr/local/lib`, but they don't work...

```
$ rdf2hdt

rdf2hdt: error while loading shared libraries: libhdt.so.0: cannot open shared object file: No such file or directory
```

**Comment by ptorrestr** [comment]
Hi,

If you do an installation in a standard directory (like `/usr/local`) you will need to execute` ldconfig` after the installation, or set `LD_LIBRARY_PATH` to` /usr/local/lib`.

It may seem to weird, but `ld` uses the file`/etc/ld.so.cache` to pick up the corresponding library. So even if a library is installed in a standard directory, it will not be linked immediately. `ldconfig` will update the cache, incorporating any new library listed in the standard directories (normally defined in`/etc/ld.so.conf.d`).

**Comment by v4ss4llo** [comment]
Works great. Sorry for the noob question.
