### ISSUE TITLE
rdf2hdt problem reading from /dev/stdin?

### ISSUE THREAD

**Issue by v4ss4llo** [rdfhdt/hdt-cpp#141]
I've run a quick test on a 1.2MB .nt file.

`rdf2hdt data.nt data.hdt` generates a HDT of size 160K

`cat data.nt | rdf2hdt /dev/stdin data.hdt` generates a HDT of size 142K

`rdf2hdt /dev/stdin data.hdt < data.nt` generates a HDT of size 160K but it's not the same file as in the first example, they have different hashes

Can somebody explain what's going on?

**Comment by LaurensRietveld** [comment]
The hash is different as the header is different (the header contains a timestamp). Had this problem before as well. Would be nice to either have the timestamp removed, or to add a content hash to the header as well.

W.r.t. piping data to an HDT: see #47 . Atm it does not work, as afaik `rdf2hdt` needs two passes over a file to create an HDT

**Comment by v4ss4llo** [comment]
Thank you.
