### ISSUE TITLE
Compilation errors on 32bit architectures

### ISSUE THREAD

**Issue by folkvir** [rdfhdt/hdt-cpp#143]
Hello,

I'm trying to install the hdt lib on a Raspberry Pi for a ldf-server usage. And I encountered a compilation error when installing _ldf-server_ or _hdt_ node library. By compiling the hdt-cpp lib on my rasp I encountered the same problem.
I previously opened an issue on hdt node lib (https://github.com/RubenVerborgh/HDT-Node/issues/14) thinking that the problem was here but this issue is  more suited for this repository.

Additional information for a normal hdt-cpp install:
* `uname -a`: Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
* `gcc -v` and `g++ -v`: gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)
* `serdi -v`: serdi 0.28.0 <http://drobilla.net/software/serd>
* no problem with ./configure

![capture du 2017-12-15 09 55 01](https://user-images.githubusercontent.com/7128943/34034273-0f295bdc-e17e-11e7-909c-50009b1537a1.png)

Hope this will help !

**Comment by ptorrestr** [comment]
Hi,

I think this is happening since your machine is armv7I, which is a 32-bit machine. Therefore `sizeof(size_t)` and `sizeof(uint32_t)` are equal, hence producing a redefinition of the functions.

As a temporal solution you may comment out one of the conflicting functions for each case.

**Comment by LaurensRietveld** [comment]
@folkvir  did the comment of ptorrestr help you? If so, we can close this issue

**Comment by folkvir** [comment]
@LaurensRietveld Yes absolutely. 👍 Thank you for the notification. I will close this issue.
