### ISSUE TITLE
Please deprecate the "develop" branch

### ISSUE THREAD

**Issue by wonkydonky** [rdfhdt/hdt-cpp#148]
The branch structure of this repository is really messy and unintelligible. It looks like you're developing the 32bit (branch: develop) and the 64bit (branch: develop-64) as two separate projects, with two different codebases. This is really a waste of time, and also very confusing for anybody who wants to contribute. The new commits merged to `develop` are not merged to `develop-64`, which means features like "automatic input format recognition" is only available for the 32bit version but not the 64bit one, and the 32bit version has removed XML support but the 64bit still has a broken implementation :/

I don't understand why you're going through this effort of supporting two separate codebases. Could you guys please clean up the branch structure, and only keep one develop branch? I don't think there is a compelling reason to maintain the `develop` branch (which can handle 2^32 triples at most) when there is already a `develop-64` branch that can handle graphs with 2^64 triples...

**Comment by mielvds** [comment]
Probably develop-64 is not stable yet? We should at least rebase/merge develop-64 more frequently en eventually merge. In the meantime, I'll check whether any other branches can be removed.

**Comment by wonkydonky** [comment]
Thank you.

**Comment by wouterbeek** [comment]
The 64-bit branch is only used to disseminate datasets that contain more than 2B triples.  E.g., [LOD-a-lot and Wikidata](http://hdt.lod.labs.vu.nl).  AFAIK I'm the only user of the 64-bit branch.

I would be very glad to see the project move to 64-bits.  With the most popular datasets in the community (DBpedia, Wikidata, Bio2RDF) all exceeding the 2B limit, the long-term relevancy of HDT may even require such a move.

The main blockade at this point may be compatibility with the Java implementation, which does not yet have a 64-bit branch.

**Comment by wonkydonky** [comment]
> The main blockade at this point may be compatibility with the Java implementation, which does not yet have a 64-bit branch.

Is this only relevant for the Java conversion tools, or is this also relevant for Fuseki? I mean... if I generate a HDT file with `develop-64`, is it possible that it won't be query-able if used with Fuseki?

**Comment by LaurensRietveld** [comment]
Exactly, the hdt files wont be compatible when it's created via the develop-64 branch, and used/queried via a non-develop-64 branch
