### ISSUE TITLE
Issue with ./configure on Fedora 27 on Ryzen

### ISSUE THREAD

**Issue by dick-twocows** [rdfhdt/hdt-cpp#149]
Getting the following when running `./configure`:

```
---snip---
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... no
configure: error: Package requirements (zlib) were not met:

Package 'zlib', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZLIB_CFLAGS
and ZLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

If I run ./configure ZLIB_CFLAGS=" " ZLIB_LIBS="-lz" it bounces the issue to;

---snip---
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... yes
checking for SERD... no
configure: error: Package requirements (serd-0 >= 0.28.0) were not met:

Package 'serd-0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SERD_CFLAGS
and SERD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

```
uname - a;
Linux ryzen.twocows 4.13.9-300.fc27.x86_64 #1 SMP Mon Oct 23 13:41:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

This is a clean OS build, am I missing something obvious.!?

**Comment by dick-twocows** [comment]
Running;

./configure ZLIB_CFLAGS=" " ZLIB_LIBS="-lz" SERD_CFLAGS=" " SERD_LIBS="-lz"

Works.!?

**Comment by dick-twocows** [comment]
Running ./make -j2;

[root@ryzen hdt-cpp]# make -j2
Making all in libcds
make[1]: Entering directory '/run/media/dick/HDD1/hdt-cpp/libcds'
Making all in .
make[2]: Entering directory '/run/media/dick/HDD1/hdt-cpp/libcds'
  CXX      src/static/bitsequence/BitSequenceBuilderDArray.lo
  CXX      src/static/bitsequence/BitSequenceBuilderRG.lo
  CXX      src/static/bitsequence/BitSequenceBuilderRRR.lo
  CXX      src/static/bitsequence/BitSequenceBuilderSDArray.lo
  CXX      src/static/bitsequence/BitSequence.lo
  CXX      src/static/bitsequence/BitSequenceDArray.lo
  CXX      src/static/bitsequence/BitSequenceRG.lo
  CXX      src/static/bitsequence/BitSequenceRRR.lo
  CXX      src/static/bitsequence/BitSequenceSDArray.lo
  CXX      src/static/bitsequence/sdarraySadakane.lo
  CXX      src/static/bitsequence/TableOffsetRRR.lo
  CXX      src/static/coders/huff.lo
src/static/coders/huff.cpp: In function ‘cds_static::THuff cds_static::loadHuff(std::istream&, int)’:
src/static/coders/huff.cpp:238:22: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
    for (d=H.depth-1;d>=0;d--) {
                     ~^~~
  CXX      src/static/coders/HuffmanCoder.lo
  CXX      src/static/mapper/MapperCont.lo
  CXX      src/static/mapper/Mapper.lo
  CXX      src/static/mapper/MapperNone.lo
  CXX      src/static/mapper/MapperRev.lo
  CXX      src/static/permutation/perm.lo
  CXX      src/static/permutation/PermutationBuilderMRRR.lo
  CXX      src/static/permutation/PermutationBuilderWT.lo
  CXX      src/static/permutation/Permutation.lo
  CXX      src/static/permutation/PermutationMRRR.lo
  CXX      src/static/permutation/PermutationWT.lo
  CXX      src/static/sequence/BitmapsSequence.lo
  CXX      src/static/sequence/SequenceAlphPart.lo
  CXX      src/static/sequence/SequenceBuilderAlphPart.lo
  CXX      src/static/sequence/SequenceBuilderGMRChunk.lo
  CXX      src/static/sequence/SequenceBuilderGMR.lo
  CXX      src/static/sequence/SequenceBuilderStr.lo
  CXX      src/static/sequence/SequenceBuilderWaveletMatrix.lo
  CXX      src/static/sequence/SequenceBuilderWaveletTree.lo
  CXX      src/static/sequence/SequenceBuilderWaveletTreeNoptrs.lo
  CXX      src/static/sequence/SequenceBuilderWaveletTreeNoptrsS.lo
  CXX      src/static/sequence/Sequence.lo
  CXX      src/static/sequence/SequenceGMRChunk.lo
  CXX      src/static/sequence/SequenceGMR.lo
  CXX      src/static/sequence/WaveletMatrix.lo
  CXX      src/static/sequence/WaveletTree.lo
  CXX      src/static/sequence/WaveletTreeNoptrs.lo
  CXX      src/static/sequence/WaveletTreeNoptrsS.lo
  CXX      src/static/sequence/wt_coder_binary.lo
  CXX      src/static/sequence/wt_coder.lo
  CXX      src/static/sequence/wt_coder_huff.lo
  CXX      src/static/sequence/wt_node.lo
  CXX      src/static/sequence/wt_node_internal.lo
  CXX      src/static/sequence/wt_node_leaf.lo
  CXX      src/static/suffixtree/factorization.lo
  CXX      src/static/suffixtree/factorization_var.lo
  CXX      src/static/suffixtree/LCP.lo
  CXX      src/static/suffixtree/LCP_DAC.lo
  CXX      src/static/suffixtree/LCP_DAC_VAR.lo
  CXX      src/static/suffixtree/LCP_FMN.lo
  CXX      src/static/suffixtree/LCP_naive.lo
  CXX      src/static/suffixtree/LCP_PhiSpare.lo
  CXX      src/static/suffixtree/LCP_PT.lo
  CXX      src/static/suffixtree/LCP_Sad.lo
src/static/suffixtree/LCP_PT.cpp: In destructor ‘virtual cds_static::LCP_PT::~LCP_PT()’:
src/static/suffixtree/LCP_PT.cpp:237:26: warning: deleting object of polymorphic class type ‘cds_static::RMQ_succinct’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
   delete (RMQ_succinct *)rmq;
                          ^~~
  CXX      src/static/suffixtree/NPR_CN.lo
  CXX      src/static/suffixtree/NPR.lo
  CXX      src/static/suffixtree/NPR_FMN.lo
  CXX      src/static/suffixtree/NSV.lo
  CXX      src/static/suffixtree/PSV.lo
  CXX      src/static/suffixtree/RMQ_succinct.lo
  CXX      src/static/suffixtree/RMQ_succinct_lcp.lo
  CXX      src/static/suffixtree/SuffixTree.lo
  CXX      src/static/suffixtree/SuffixTreeY.lo
  CXX      src/static/textindex/comparray4.lo
src/static/suffixtree/SuffixTreeY.cpp: In destructor ‘virtual cds_static::SuffixTreeY::~SuffixTreeY()’:
src/static/suffixtree/SuffixTreeY.cpp:464:26: warning: deleting object of polymorphic class type ‘cds_static::TextIndexCSA’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
   delete (TextIndexCSA *)csa;
                          ^~~
  CXX      src/static/textindex/mmap.lo
  CXX      src/static/textindex/qsufsort.lo
  CXX      src/static/textindex/suftest3.test.lo
  CXX      src/static/textindex/TextIndex.lo
src/static/textindex/suftest3.test.cpp: In function ‘char* cds_static::error_index(int)’:
src/static/textindex/suftest3.test.cpp:389:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
    case 23: printf(error, "Cannot open index; break");
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/static/textindex/suftest3.test.cpp:390:4: note: here
    case 24: printf(error, "Cannot open text; break");
    ^~~~
src/static/textindex/suftest3.test.cpp:390:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
    case 24: printf(error, "Cannot open text; break");
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/static/textindex/suftest3.test.cpp:391:4: note: here
    case 25: printf(error, "Error reading the index"); break;
    ^~~~
  CXX      src/static/textindex/TextIndexCSA.lo
  CXX      src/utils/Array.lo
  CXX      src/utils/BitString.lo
  CXX      src/utils/cppUtils.lo
  CXX      src/utils/timing.lo
  CXXLD    libcds.la
make[2]: Leaving directory '/run/media/dick/HDD1/hdt-cpp/libcds'
Making all in tests
make[2]: Entering directory '/run/media/dick/HDD1/hdt-cpp/libcds/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/run/media/dick/HDD1/hdt-cpp/libcds/tests'
make[1]: Leaving directory '/run/media/dick/HDD1/hdt-cpp/libcds'
Making all in libhdt
make[1]: Entering directory '/run/media/dick/HDD1/hdt-cpp/libhdt'
Making all in .
make[2]: Entering directory '/run/media/dick/HDD1/hdt-cpp/libhdt'
  CXX      src/bitsequence/libhdt_la-BitSequence375.lo
  CXX      src/dictionary/libhdt_la-FourSectionDictionary.lo
  CXX      src/dictionary/libhdt_la-KyotoDictionary.lo
  CXX      src/dictionary/libhdt_la-LiteralDictionary.lo
  CXX      src/dictionary/libhdt_la-PlainDictionary.lo
In file included from /usr/include/c++/7/ext/hash_map:60:0,
                 from src/dictionary/PlainDictionary.hpp:46,
                 from src/dictionary/PlainDictionary.cpp:34:
/usr/include/c++/7/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^~~~~~~
  CXX      src/hdt/libhdt_la-BasicHDT.lo
In file included from src/hdt/../util/fileUtil.hpp:37:0,
                 from src/hdt/BasicHDT.cpp:39:
./include/../third/gzstream.h:38:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1116: src/hdt/libhdt_la-BasicHDT.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/run/media/dick/HDD1/hdt-cpp/libhdt'
make[1]: *** [Makefile:1582: all-recursive] Error 1
make[1]: Leaving directory '/run/media/dick/HDD1/hdt-cpp/libhdt'
make: *** [Makefile:428: all-recursive] Error 1
[root@ryzen hdt-cpp]#

**Comment by ptorrestr** [comment]
Hi,

You need to install `zlib` (dev package) and `serd`. When you set the flags, the `configure` script won't check if this flags are correct or not. They are going to be send directly to the `make` script. Thus, I'm guessing the compilation is going to fail. 

The easy way is to this is install the standard `zlib` development package of your distro (it has to include a `.so` file) and install `serd` in the default folder.

To make sure `pkgconfig` is reading the proper paths, you can set `PKG_CONFIG_PATH` as shown in file [travis.yml](https://github.com/rdfhdt/hdt-cpp/blob/develop/.travis.yml)

**Comment by dick-twocows** [comment]
Ok, zlib happy, but serd is installed and I still get the same;

dnf install zlib-devel

---snip---
Installed:
  zlib-devel.x86_64 1.2.11-4.fc27

But;

checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... yes
checking for SERD... no
configure: error: Package requirements (serd-0 >= 0.28.0) were not met:

Package 'serd-0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SERD_CFLAGS
and SERD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
[root@ryzen hdt-cpp]# dnf install serd
Last metadata expiration check: 2:49:54 ago on Wed 03 Jan 2018 13:30:37 GMT.
Package serd-0.28.0-2.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by ptorrestr** [comment]
I think you should use [serd-devel](https://fedora.pkgs.org/27/fedora-x86_64/serd-devel-0.28.0-2.fc27.x86_64.rpm.html).  Seems that `serd` package does not include the pkg-config file and thus it cannot be identified by the configure script.

**Comment by dick-twocows** [comment]
You got there before me!

dnf install serd-devel

Installed:
  serd-devel.x86_64 0.28.0-2.fc27

**Comment by wonkydonky** [comment]
The dependencies are described in the [README](https://github.com/rdfhdt/hdt-cpp#prerequisites).

**Comment by wouterbeek** [comment]
@dick-twocows From the looks of it this issue your problem has been solved for you?  If so, then please close the issue (and if not: let us know how we can help you further).
