### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#150]
Just an issue to discuss the new release. The most significant change is the changed directory structure and building process (thanks to @ptorrestr )
All resulting bugs have been resolved, so I suggest to release develop to master to avoid bloating the develop branch with more enhancements.

To discuss: will this be a minor or major release? I'd opt for a major release (1.2.0 > 2.0.0)

**Comment by RubenVerborgh** [comment]
> To discuss: will this be a minor or major release?

Answering this question in a semver way: did we introduce breaking interface changes? If yes, major.
If no, did we introduce new API functionality? If yes, minor. If no, patch.

We don't _have_ to do semver though. Another option discussed at https://github.com/rdfhdt/hdt-cpp/issues/83#issuecomment-324659557 was for the major version number to reflect the HDT version. By that logic, we should still keep 1.x.

**Comment by LaurensRietveld** [comment]
I forgot about our previous discussion w.r.t. version numbering. Let's not revisit that, as I'm happy with the decision not to follow semver and make the major version number reflect the HDT version.

**Comment by RubenVerborgh** [comment]
So I'd then propose: if interface changes, minor bump; patch otherwise. And release patch versions more frequently (cfr. RubenVerborgh/HDT-Node#19).

**Comment by LaurensRietveld** [comment]
I'll release this weekend, will do a minor bump here. There aren't changes in the c++ api, but there might be some other breaking changes  (changed dir structure, removal of raptor as possible dep)

**Comment by LaurensRietveld** [comment]
Released as 1.3.0
