### ISSUE TITLE
Duplicate triples not taking into account

### ISSUE THREAD

**Issue by D063520** [rdfhdt/hdt-cpp#155]
Hi,

I just noticed a strange behaviour. If I put in a file:

\<http://C1> \<http://link1> \<http://C1> .
\<http://S1> \<http://link1> \<http://O1> .
\<http://S4> \<http://link1> \<http://S3> .
\<http://S3> \<http://link1> \<http://S3> .
\<http://S3> \<http://link1> \<http://S3> .
\<http://S3> \<http://link1> \<http://S3> .
\<http://S3> \<http://link1> \<http://S4> .

and generate the HDT using rdf2hdt and I then query it using hdtSearch then I find only 5 triples and not 7. The duplicate triples are lost. Is this expected behaviour?

Thank you

**Comment by akuckartz** [comment]
Yes, that is the behavior I expect from a triple store.

**Comment by D063520** [comment]
But should:

SELECT count(*) where {
   <http://S3> <http://link1> <http://S3> .
}

not give back 3?

**Comment by akuckartz** [comment]
1

**Comment by LaurensRietveld** [comment]
Semantically, they are the same (even if syntactically you duplicate them). So yes, this is expected behaviour
