### ISSUE TITLE
error and bad results of a simple triple pattern search

### ISSUE THREAD

**Issue by gezsi** [rdfhdt/hdt-cpp#156]
Dear HDT Developers,

After a clean install of the current version of HDT (Jan 31, 2018), I found a strange behaviour of the tool. Namely, I tried to find the following pattern in the attached RDF database ([rdf.zip](https://github.com/rdfhdt/hdt-cpp/files/1683538/rdf.zip)), and that resulted a lot of non-existing triple patterns and finally an error message: 'Trying to get an element bigger than the array.'.
I tried to reproduce it with the hdtSearch tool, but only managed to reproduce it when I commented out the 'it->skip(offset)' line in the iterate function. (Otherwise it resulted 0 matching patterns, but that's because this function call throws an exception and the search while loop is not executed.)

The pattern was: 

> ? http://semanticprioritizer.org/semanticprioritizer_vocabulary:endpoint http://task.semanticprioritizer.org/NodeDisease

Some info:

- Linux *** 3.19.0-25-generic #26 14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
- no problem with install

Any help would be much appreciated!

Thanks,
András

**Comment by LaurensRietveld** [comment]
Thanks for the report András, this issue is fixed in the develop branch
