### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#158]
I'm unable to compile this library:

```
$ echo $SERD_LIBS
-L/home/wbeek/git/serd/build -lserd-0
$ echo $SERD_CFLAGS
-I/home/wbeek/git/serd/serd
$ ./configure
configure: error: Package requirements (serd-0 >= 0.28.0) were not met:
Package 'serd-0', required by 'virtual:world', not found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables SERD_CFLAGS
and SERD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I seem to have all the files in place:

```
$ ls /home/wbeek/git/serd/build
c4che  compile_commands.json  config.log  libserd-0.so  libserd-0.so.0  libserd-0.so.0.29.2  serd-0.pc  serd_config.h  serdi  src
$ ls /home/wbeek/git/serd/serd
serd.h
```

And my Serd version is fine as well:

```
$ serdi -v
serdi 0.29.2 <http://drobilla.net/software/serd>
```

Any hints on what I am doing wrong here?  Thanks in advance.

**Comment by ptorrestr** [comment]
Try to check the logs produced by configure. 

Can you try set 'PKG_CONFIG_PATH' to '/home/wbeek/git/serd/build'

**Comment by sharpaper** [comment]
Can't you just link the library dynamically? It should already be available in any distro repos.

**Comment by ljos** [comment]
Did you export the variables? =configure= runs in a new shell so the two variables needs to be exported. Alternatively you could try to run
```
./configure SERD_LIBS="-L/home/wbeek/git/serd/build/ -lserd-0" SERD_CFLAGS="-I/home/wbeek/git/serd/serd"
```

That works on the develop branch for me.

**Comment by ljos** [comment]
Actually, in this instance it fails on make, but I think I did something wrong.

**Comment by ljos** [comment]
Scratch that; from a clean and newly downloaded repo what I suggested does work.

**Comment by wouterbeek** [comment]
Thanks for the useful feedback!  My issue is solved now.

@ptorrestr The following lines appear in my `config.log`:

```
Package serd-0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `serd-0.pc'
to the PKG_CONFIG_PATH environment variable
```

Setting `PKG_CONFIG_PATH` was indeed the solution here.  After installing Serd according to the regular procedure (`./waf configure` then `./waf` then `sudo ./waf install`), the file `serd-0.pc` was located in `/usr/local/lib/pkgconfig/`.  Why is `./configure` not able to find it there?  Maybe Serd could install its files in another location where it can be more easily found?

@sharpaper Yes, you're right: installing Serd from distros is the preferred approach.  Unfortunately, my distros offer somewhat outdated versions of Serd (0.28.0 in Fedora and 0.22.0 in Ubuntu LTS).

@ljos Thanks for the info that `./configure` runs in a separate shell (this means that my exports may have had zero effect on it to begin with...).  I also was not aware that you can set the environment variables as part of the `./configure` invocation, in the way you show in your example.
