### ISSUE TITLE
Improve serd/hdt-cpp alignment WRT pkg-config

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#162]
Based on observations in issues #149 and #158, it turns out that we sometimes have to set the `PKG_CONFIG_PATH` in order to find the `serd-0.pc` file (e.g., on my machine this file is in `/usr/local/lib/pkgconfig/`).

@ptorrestr made the following observation:

> Seems that serd package does not include the pkg-config file and thus it cannot be identified by the configure script.

Can the issues referred to above be avoided by "including a pkg-config file" in Serd?  This may be something Serd maintainer @drobilla is willing to help us out with.

**Comment by drobilla** [comment]
Serd includes and installs a pkg-config file to the install prefix as usual.

Usually this comes up with distributions that have a `pkg-config` that is configured to not look in `/usr/local/lib/pkgconfig` by default, requiring `PKG_CONFIG_PATH` to be set.  IIRC this is the case with at least Redhat-inspired distributions.  I have no idea why, but it's not a serd issue (`/usr/local` is the standard prefix, you can specify another one at configure time if you want, but installing manual things over `/usr` is not a good idea).

You could maybe ram `/usr/local` in there in the hdt build scripts to avoid this, but I'm not sure if that's a great idea.  Probably should just be well documented.

**Comment by wouterbeek** [comment]
Thanks for your comments @drobilla.  This should be taken care of by the recent additions to the README file (commit 70e8fa410aa6e716a17867090c2be444cc2604da).
