### ISSUE TITLE
Wrong path for binaries

### ISSUE THREAD

**Issue by SvenSvenson** [rdfhdt/hdt-cpp#163]
https://github.com/rdfhdt/hdt-cpp/blob/23fcd286da69f809942ee84c31739bf2b453602e/Dockerfile#L29

When running the  docker container (let's say we called it hdt) with `docker run hdt rdf2hdt` the following error message occurs: `executable file not found in $PATH`.

Apparently the path for the binaries is wrong in the Dockerfile, instead of 
`ENV PATH /usr/local/src/hdt-cpp/hdt-lib/tools:$PATH`

it should be

`ENV PATH /usr/local/src/hdt-cpp/libhdt/tools:$PATH`

**Comment by LaurensRietveld** [comment]
Thanks for the report, this is fixed in the dev branch now
