### ISSUE TITLE
Migrate to 64 bit branch

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#175]
As others mentioned as well, the branches in this repo can be a bit confusing as we've got two branches with active development/PRs (develop and develop-64)
How about moving the 64 develop branch gradually to master? 

I'm using the 64 bit branch intensively myself and haven't encountered any issues. 
Haven't encountered any issue with reading files (in develop-64) created by the master branch as well.

Can't speak for compatability with Java though, as I'm not using that part of the hdt codebase.

@rdfhdt/commiters any experience with using the develop-64 branch, and using the created files in other libs like hdt-java? And, any thoughts about starting the process to start the process of migrating to the develop-64 code?

**Comment by RubenVerborgh** [comment]
No objections from my side.

However, does this branch result in a different HDT format? If so, we should update the major version counter (and, because of that, also consult with the HDT creators).

**Comment by LaurensRietveld** [comment]
I've just merged the develop-64 branch to the develop branch

**Comment by mielvds** [comment]
Could you cleanup the branches as well?

**Comment by LaurensRietveld** [comment]
Jep, it's on my list. Have to clean up some direct dependencies of mine on the 64 branch first (and give others the opportunity to do the same as well)

**Comment by mielvds** [comment]
https://github.com/rdfhdt/hdt-cpp/tree/long-dict-id can go now? I think it was the base for the other 64bit branch that is now deleted.

**Comment by LaurensRietveld** [comment]
You're right, I've deleted that one as well
