### ISSUE TITLE
configure: error: Package requirements (serd-0 >= 0.28.0) were not met:

### ISSUE THREAD

**Issue by cobucci** [rdfhdt/hdt-cpp#190]
After doing everthing that is in the README.md, i'm getting this error when running ./configure:

 configure: error: Package requirements (serd-0 >= 0.28.0) were not met:

Requested 'serd-0 >= 0.28.0' but version of Serd is 0.22.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SERD_CFLAGS
and SERD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

what should i do?

**Comment by mielvds** [comment]
Simply upgrade your Serd (see https://github.com/rdfhdt/hdt-cpp/issues/177). You can build from scratch: https://github.com/drobilla/serd/releases/tag/v0.30.0
