### ISSUE TITLE
Issue compiling with Kyotocabinet

### ISSUE THREAD

**Issue by bjonnh** [rdfhdt/hdt-cpp#197]
using kyotocabinet libkyotocabinet16v5 from ubuntu 18.10
--- log

In file included from src/dictionary/KyotoDictionary.cpp:38:
src/dictionary/KyotoDictionary.hpp:108:18: error: conflicting return type specified for ‘virtual unsigned int hdt::KyotoDictionary::getMapping()’
     unsigned int getMapping();
                  ^~~~~~~~~~
In file included from src/dictionary/KyotoDictionary.hpp:36,
                 from src/dictionary/KyotoDictionary.cpp:38:
./include/Dictionary.hpp:171:20: note: overridden function is ‘virtual size_t hdt::Dictionary::getMapping()’
     virtual size_t getMapping()=0;
                    ^~~~~~~~~~
src/dictionary/KyotoDictionary.cpp:376:8: error: no declaration matches ‘size_t hdt::KyotoDictionary::getGlobalId(size_t, size_t, hdt::DictionarySection)’
 size_t KyotoDictionary::getGlobalId(size_t mapping, size_t id, DictionarySection position) {
        ^~~~~~~~~~~~~~~
In file included from src/dictionary/KyotoDictionary.cpp:38:
src/dictionary/KyotoDictionary.hpp:122:12: note: candidates are: ‘size_t hdt::KyotoDictionary::getGlobalId(size_t, hdt::DictionarySection)’
     size_t getGlobalId(size_t id, DictionarySection position);
            ^~~~~~~~~~~
src/dictionary/KyotoDictionary.hpp:121:12: note:                 ‘size_t hdt::KyotoDictionary::getGlobalId(unsigned int, size_t, hdt::DictionarySection)’
     size_t getGlobalId(unsigned int mapping, size_t id, DictionarySection position);
            ^~~~~~~~~~~
src/dictionary/KyotoDictionary.hpp:54:7: note: ‘class hdt::KyotoDictionary’ defined here
 class KyotoDictionary : public ModifiableDictionary {
       ^~~~~~~~~~~~~~~
src/dictionary/KyotoDictionary.cpp:514:8: error: no declaration matches ‘size_t hdt::KyotoDictionary::getMapping()’
 size_t KyotoDictionary::getMapping() {
        ^~~~~~~~~~~~~~~
In file included from src/dictionary/KyotoDictionary.cpp:38:
src/dictionary/KyotoDictionary.hpp:108:18: note: candidate is: ‘virtual unsigned int hdt::KyotoDictionary::getMapping()’
     unsigned int getMapping();
                  ^~~~~~~~~~
src/dictionary/KyotoDictionary.hpp:54:7: note: ‘class hdt::KyotoDictionary’ defined here
 class KyotoDictionary : public ModifiableDictionary {
       ^~~~~~~~~~~~~~~
In file included from src/hdt/BasicModifiableHDT.hpp:24,
                 from src/hdt/HDTFactory.cpp:34:
src/hdt/../dictionary/KyotoDictionary.hpp:108:18: error: conflicting return type specified for ‘virtual unsigned int hdt::KyotoDictionary::getMapping()’
     unsigned int getMapping();
                  ^~~~~~~~~~
In file included from ./include/HDT.hpp:40,
                 from src/hdt/HDTFactory.cpp:28:
./include/Dictionary.hpp:171:20: note: overridden function is ‘virtual size_t hdt::Dictionary::getMapping()’
     virtual size_t getMapping()=0;
                    ^~~~~~~~~~
In file included from src/hdt/BasicModifiableHDT.hpp:24,
                 from src/hdt/BasicModifiableHDT.cpp:8:
src/hdt/../dictionary/KyotoDictionary.hpp:108:18: error: conflicting return type specified for ‘virtual unsigned int hdt::KyotoDictionary::getMapping()’
     unsigned int getMapping();
                  ^~~~~~~~~~
In file included from ./include/HDT.hpp:40,
                 from src/hdt/BasicModifiableHDT.hpp:12,
                 from src/hdt/BasicModifiableHDT.cpp:8:
./include/Dictionary.hpp:171:20: note: overridden function is ‘virtual size_t hdt::Dictionary::getMapping()’
     virtual size_t getMapping()=0;
                    ^~~~~~~~~~
In file included from src/hdt/BasicHDT.cpp:46:
src/hdt/../dictionary/KyotoDictionary.hpp:108:18: error: conflicting return type specified for ‘virtual unsigned int hdt::KyotoDictionary::getMapping()’
     unsigned int getMapping();
                  ^~~~~~~~~~
In file included from ./include/HDT.hpp:40,
                 from src/hdt/HDTFactory.hpp:36,
                 from src/hdt/BasicHDT.cpp:42:
./include/Dictionary.hpp:171:20: note: overridden function is ‘virtual size_t hdt::Dictionary::getMapping()’
     virtual size_t getMapping()=0;
                    ^~~~~~~~~~

**Comment by mielvds** [comment]
Closing in favor of https://github.com/rdfhdt/hdt-cpp/issues/206
