### ISSUE TITLE
Document the HDT syntax format

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#205]
People new to HDT sometimes incorrectly expect it to follow N-Triples, or even Turtle, syntax.

HDT syntax is different, here's a comparison:

```
| *Term type*             | *Turtle*     | *N-Triples* | *HDT*    |
|-------------------------+--------------+-------------+----------|
| IRI                     | <…>          | <…>         | …        |
| abbreviated IRI         | …:…          |             |          |
| typed literal           | "…"^^<…>     | "…"^^<…>    | "…"^^<…> |
|                         | """…"""^^<…> |             |          |
|                         | '…'^^<…>     |             |          |
|                         | '''…'''<…>   |             |          |
| language-tagged string  | "…"@…        | "…"@…       | "…"@…    |
|                         | """…"""@…    |             |          |
|                         | '…'@…        |             |          |
|                         | '''…'''@…    |             |          |
| abbreviated rdf:type    | a            |             |          |
| abbreviated xsd:boolean | true         |             |          |
| abbreviated xsd:decimal | -1.1         |             |          |
| abbreviated xsd:double  | -1.1E-1      |             |          |
|                         | -1.1e-1      |             |          |
| abbreviated xsd:integer | -01          |             |          |
| abbreviated xsd:string  | "…"          | "…"         | *        |
|                         | """…"""      |             |          |
|                         | '…'          |             |          |
|                         | '''…'''      |             |          |
```

* Allowed in previous HDT versions, resulting in duplicate triples / loss of the set feature.  After pull request https://github.com/rdfhdt/hdt-cpp/pull/185 this notation is no longer supported.

**Comment by mielvds** [comment]
The comment on N3.js (> 1.0) no longer holds as all internal representation is now a RDFJS object, not a string. The HDT-Node implementation, however, is no longer in sync and thus uses N3js prior to RDFJS (~ 0.11).  I actually opened an issue about having HDT-Node spitting out RDFJS as well: https://github.com/RubenVerborgh/HDT-Node/issues/35

But so as far I understood the table, it's only the missing datatype brackets <...> right? I also found that one difference very confusing in practice

**Comment by wouterbeek** [comment]
@mielvds You're right, but with the added caveat that the brackets are only missing for IRIs that do not appear as datatype IRIs in literals.

I've removed N3.js syntax, since I now understand this syntax is outdated anyway, and I am not sufficiently familiar with it to document it reliably.

I've also updated the cell for abbreviated XSD string notation, which will no longer be supported after your pull request <https://github.com/rdfhdt/hdt-cpp/pull/185>.

**Comment by mielvds** [comment]
@wouterbeek I'm not sure I follow. Abbreviated datatypes or plain literals will still be supported, they are simply be stored differently (= correctly as they prevent invalid duplicates) now. But a user of HDT should not notice and can still turn a document full of `xsd:string` datatypes into an HDT.

About the table: since this is for documentation, I'd keep the HDT-Node entry for legacy reasons. Once HDT-Node has synced with the new N3js, we can turn that into HDT-Node (< 1.0) and HDT-Node (1.0+) or something.

**Comment by wouterbeek** [comment]
@mielvds Good point, since this is only about the internal format, users of HDT need not worry too much about the above table; closing...
