### ISSUE TITLE
Segmentation fault (724M quads / 128 GB RAM)

### ISSUE THREAD

**Issue by ColinMaudry** [rdfhdt/hdt-cpp#215]
Hello!

I'm trying to publish the French company register SIRENE as RDF, via an HDT file exposed with an LDF interface: https://github.com/ColinMaudry/sirene-ld (the README is not completely up-to-date regarding the progress, but [the code on branch develop](https://github.com/ColinMaudry/sirene-ld/tree/develop) is). I will then build a Web app to publish resource a URIs and an interface to query the data ([sirene-ld-web](https://github.com/ColinMaudry/sirene-ld-web/)).

The RDF I'm working with (724M quads) is here: https://sireneld.io/data/sirene/

The server I use to convert it to HDT is [Scaleway's GP1-L](https://www.scaleway.com/en/virtual-instances/general-purpose/) (128 GB RAM).

Here is how it went:

```
rdf2hdt -V
v1.1.2 (built on updated Ubuntu Bionic and branch develop)

rdf2hdt -i -f nq rdf/sireneld.nq.gz hdt/sireneld.nq.hdt
```

After 20 minutes, it failed with the following message:

```
line 6:  4426 Segmentation fault      (core dumped) rdf2hdt -i -f nq rdf/sireneld.nq.gz hdt/sireneld.nq.hdt
```

The memory usage had peaked at 69G/128G (+/- 30 seconds) (- 330M base RAM consumption):

```
free -h
              total        used        free      shared  buff/cache   available
Mem:           125G         69G         51G        720K        5.0G         55G
Swap:            0B          0B          0B
```

Questions:

- is develop the "best" branch to build from?
- is feeding gzipped nquads to rdf2hdt less stable than uncompressed ntriples or turtle?
- any clue on what went wrong?

Thanks.

**Comment by ColinMaudry** [comment]
Same result with uncompressed nquads.

**Comment by ColinMaudry** [comment]
HDT generation worked well with triples instead of quads (.nt instead of .nq). I wasn't stuck to my screen, but I believe it didn't peak at more than 32G out of 128G. Processing quads is another league!

Result is here: https://sireneld.io/data/sirene/

**Comment by ColinMaudry** [comment]
I can work without graphs, but I had thought my application with them, and I assumed (?) that graph queries would perform better.

Does anyone have feedback regarding HDT LDF querying triples vs. quads?

**Comment by AxelPolleres** [comment]
For quad support, you may want to look here:
Javier D. Fernandez, Miguel A. Martínez-Prieto, Axel Polleres, and Julian Reindorf. HDTQ: Managing RDF datasets in compressed space. In Aldo Gangemi, Roberto Navigli, Maria-Esther Vidal, Pascal Hitzler, Raphaël Troncy, Laura Hollink, Anna Tordai, and Mehwish Alam, editors, Proceedings of the 15th European Semantic Web Conference (ESWC2018), volume 10843 of Lecture Notes in Computer Science (LNCS), pages 191--208, Heraklion, Greece, June 2018. Springer.
http://polleres.net/publications/fern-etal-ESWC2018.pdf

may be helpful, algthough I have to admit that Javier and Julian did all the coding,
Axel
--
url: http://www.polleres.net/  twitter: @AxelPolleres

**Comment by ColinMaudry** [comment]
Thanks @AxelPolleres, I scanned through the paper and it looks very promising.

Do you think an HDTQ archive produced with [hdtq-java](https://github.com/JulianRei/hdtq-java) would work with a LinkedDataFragments server such as https://github.com/LinkedDataFragments/Server.js? I'll give it a try.

cc @julianrei @rubensworks

**Comment by rubensworks** [comment]
FYI, as of recently, the LDF server supports quads. AFAIK, no C++/Node.js implementation for HDTQ exists yet, but once it does, we'd love to add support for it into the server.

**Comment by AxelPolleres** [comment]
--
url: http://www.polleres.net/  twitter: @AxelPolleres

> On 21.04.2020, at 17:02, Ruben Taelman <notifications@github.com> wrote:
> 
> 
> FYI, as of recently, the LDF server supports quads.

Cool!

> AFAIK, no C++/Node.js implementation for HDTQ exists yet, but once it does, we'd love to add support for it into the server.

Unfortunately, no other plans/ressources to port on our end at this point, but would be great, indeed!
Volunteers welcome :-)

Axel

**Comment by ColinMaudry** [comment]
I've successfully created an HDTQ file with hdtq-java:

```
bin/rdf2hdt.sh sireneld.nq sireneld.hdt
```

Indeed when I try to use it with `comunica-sparql-hdt-http`:

```
comunica-sparql-hdt-http -l debug "{ \"sources\": [{ \"type\": \"hdtFile\", \"value\" : \"/path/to/sireneld.hdt \" }]}"

Server running on http://localhost:3000/
[200] POST to /sparql
      Requested media type: null
      Received query: select ?s where { graph ?graph  {?s ?p ?o  }} limit 10
[500] Server error in results: Error: Could not open HDT file "/path/to/sireneld.hdt" 
```

So no HDTQ support yet in LDF.

@rubensworks what sort of source would you suggest for best quad querying performance with an LDF server? Given the size of my dataset, a SPARQL endpoint would require too much disk space for my hardware... Hence my initial choice of HDT.

**Comment by ColinMaudry** [comment]
I've successfully created an HDTQ file with hdtq-java:

```
bin/rdf2hdt.sh sireneld.nq sireneld.hdt
```

Indeed when I try to use it with `comunica-sparql-hdt-http`:

```
comunica-sparql-hdt-http -l debug "{ \"sources\": [{ \"type\": \"hdtFile\", \"value\" : \"/path/to/sireneld.hdt \" }]}"

Server running on http://localhost:3000/
[200] POST to /sparql
      Requested media type: null
      Received query: select ?s where { graph ?graph  {?s ?p ?o  }} limit 10
[500] Server error in results: Error: Could not open HDT file "/path/to/sireneld.hdt" 
```

So no HDTQ support yet in LDF.

@rubensworks what sort of source would you suggest for best quad querying performance with an LDF server? Given the size of my dataset, a SPARQL endpoint would require too much disk space for my hardware... Hence my initial choice of HDT.

**Comment by ColinMaudry** [comment]
I've successfully created an HDTQ file with hdtq-java:

```
bin/rdf2hdt.sh sireneld.nq sireneld.hdt
```

Indeed when I try to use it with `comunica-sparql-hdt-http`:

```
comunica-sparql-hdt-http -l debug "{ \"sources\": [{ \"type\": \"hdtFile\", \"value\" : \"/path/to/sireneld.hdt \" }]}"

Server running on http://localhost:3000/
[200] POST to /sparql
      Requested media type: null
      Received query: select ?s where { graph ?graph  {?s ?p ?o  }} limit 10
[500] Server error in results: Error: Could not open HDT file "/path/to/sireneld.hdt" 
```

So no HDTQ support yet in LDF.

@rubensworks what sort of source would you suggest for best quad querying performance with an LDF server? Given the size of my dataset, a SPARQL endpoint would require too much disk space for my hardware... Hence my initial choice of HDT.

**Comment by ColinMaudry** [comment]
I've successfully created an HDTQ file with hdtq-java:

```
bin/rdf2hdt.sh sireneld.nq sireneld.hdt
```

Indeed when I try to use it with `comunica-sparql-hdt-http`:

```
comunica-sparql-hdt-http -l debug "{ \"sources\": [{ \"type\": \"hdtFile\", \"value\" : \"/path/to/sireneld.hdt \" }]}"

Server running on http://localhost:3000/
[200] POST to /sparql
      Requested media type: null
      Received query: select ?s where { graph ?graph  {?s ?p ?o  }} limit 10
[500] Server error in results: Error: Could not open HDT file "/path/to/sireneld.hdt" 
```

So no HDTQ support yet in LDF.

@rubensworks what sort of source would you suggest for best quad querying performance with an LDF server? Given the size of my dataset, a SPARQL endpoint would require too much disk space for my hardware... Hence my initial choice of HDT.

**Comment by ColinMaudry** [comment]
@rubensworks If you will, let's continue in https://github.com/ColinMaudry/sirene-ld/issues/39 :slightly_smiling_face:
