### ISSUE TITLE
ERROR: std::bad_alloc

### ISSUE THREAD

**Issue by ahmad88me** [rdfhdt/hdt-cpp#216]
While running hdtSearch, I got the the following error:
```
Predicate Bitmap in 20 sec 445 ms 408 us%                                       
Count predicates in 1 min 50 sec 968 ms 573 us4.298 %                        
Count Objects in 2 min 12 sec 845 ms 849 us Max was: 12278145                
Bitmap in 3 sec 878 ms 584 us2 % / 48.472 %                       
Bitmap bits: 1040358853 Ones: 206201072
ERROR: std::bad_alloc
```
hdt-cpp version: `1.3.3`
dataset: `DBPedia 2016-04 English`

**Comment by dinikolop** [comment]
If I am not mistaken, this is a typical error when there is not enough of available memory. There are certainly scalability limitations. Large graphs such as DBPedia might exceed the memory limits when the index file is being created through `hdtSearch`. 
The was a similar comment here": https://github.com/rdfhdt/hdt-cpp/issues/121#issuecomment-340250962 but unfortunately no answer w.r.t. a report of these limitations. 
Maybe for now, making sure that there is enough free memory in your machine (or another laptop/server), or increasing the swap space could create the index file.

**Comment by ahmad88me** [comment]
Thanks @dinikolop , downloading the index file from the website worked for us :)
