### ISSUE TITLE
Accept gzipped RDF input

### ISSUE THREAD

**Issue by jaw111** [rdfhdt/hdt-cpp#217]
When working with large datasets, it'd be useful to work with compressed input files rather than having the whole file uncompressed on disk.

I'm typically working with gzipped N-Triples, so ideally one could use command like `rdf2hdt -z -f=nt input.nt.gz output.hdt` where `-z` flag indicates gzipped input.

**Comment by dinikolop** [comment]
Isn't that the case already? Do you get an error when you try something like:
```bash
$ rdf2hdt input.nt.gz output.hdt
```
, on a small file?

**Comment by jaw111** [comment]
It works! Awesome :)

Delving into the code it seems a bit of an happy accident though?

https://github.com/rdfhdt/hdt-cpp/blob/develop/libhdt/tools/rdf2hdt.cpp#L173

Would this still work if it the gzipped input was in another serialization?

**Comment by dinikolop** [comment]
As far as I am concerned, it will still work. You can specify the appropriate RDF format with the `-f` argument:
```sh
-f	<format>	Format of the RDF input (nquads,nq,ntriples,nt,trig,turtle,ttl)
```

**Comment by jaw111** [comment]
true, would be useful if the readme and/or help were extended to show this is possible to stop people like me asking questions.
