### ISSUE TITLE
Triple pattern query does not return results for SP? patterns with large dataset

### ISSUE THREAD

**Issue by jaw111** [rdfhdt/hdt-cpp#218]
I ran into an odd issue where some queries on a large HDT file do not return the expected results.

For example, if I query a pattern with a fixed subject `1 ? ?` then i get results:

```
1 5 2
1 6 3
1 7 4
```

So those statements are 'in' the HDT.

However, if I query a pattern with fixed subject and predicate `1 5 ?` then I get zero results. Similarly zero results for a `1 5 2` query.

This only happens for subjects 'after' a certain point in the file.

The dataset I am using contains over 3 billion statements of which no statements share the same subject and predicate. It is not public data, so I cannot share it.

The counts from the header are:

```
<file:///source/data.nt.gz> <http://rdfs.org/ns/void#triples> "3255911749" .
<file:///source/data.nt.gz> <http://rdfs.org/ns/void#properties> "21" .
<file:///source/data.nt.gz> <http://rdfs.org/ns/void#distinctSubjects> "658001921" .
<file:///source/data.nt.gz> <http://rdfs.org/ns/void#distinctObjects> "723185425" .
```

Having delved into the [technical overview of HDT internals](http://www.rdfhdt.org/hdt-internals/) it appears to be the case that to handle a SP? query one needs to maintain a counter that effectively represents the unique subject-predicate combinations to be able to scan the bit sequence (Bo) for the object layer. 

The observation with our dataset is those queries fail to produce the expected results *somewhere* around the 2.1B mark, so perhaps a 32-bit signed integer is used for that count (which can only represent integers up to 2,147,483,647).

**Comment by mielvds** [comment]
The issue should start somewhere in the BitmapTriplesSearchIterator: https://github.com/rdfhdt/hdt-cpp/blob/develop/libhdt/src/triples/BitmapTriplesIterators.cpp

There's a lot of size_t datatype and that should scale according to the compiler used.

**Comment by jaw111** [comment]
For example I note in `MiddleWaveletIterator::skip` that:

1. `numJumps` is defined as `int` (line 457) whilst it gets assigned values that can be size_t
2. `posLeft` is defined as `unsigned int` (line 458) whilst it gets assigned values that can be size_t

That in itself seems inconsistent, but I really have no clue how `skip` is used and how any overflow could manifest.

**Comment by jaw111** [comment]
Closing this out as it was tracked down to an outdated dependency in [HDT-Node](https://github.com/RubenVerborgh/HDT-Node) rather than an issue in the HDT C++ implementation.
