### ISSUE TITLE
Dockerfile fails on building serd

### ISSUE THREAD

**Issue by vlcinsky** [rdfhdt/hdt-cpp#223]
Building docker image fails:
```shell
$ docker build .
```
It fails on building serd as the tar.gz archive of serd does not contain submodule `waflib` used to control the build of libs and executables.

The solution is to replaced downloading of specific `serd` source archive with git clone and then doing `git submodule update --recursive --init`

**Comment by drobilla** [comment]
This is (as far as I know) a universal and unavoidable issue with both Github and Gitlab generated tarballs for repositories that use submodules.  I'm not sure if or how that would have ever worked.

The "real" release tarballs at http://download.drobilla.net/ are self-contained and have no build dependencies other than Python.

**Comment by vlcinsky** [comment]
What to do next?

My PR #224 is using shallow git clone and includes other improvements (better docker builds due to cache, documentation in README).

Options I see now:
- (preferred) accept the PR as is.
- modify the PR to use download from http://download.drobilla.net
- reject the PR

**Comment by drobilla** [comment]
Either of the first two approaches is fine by me anyway.
