### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by kinghuang** [rdfhdt/hdt-cpp#227]
It looks like development on hdt-cpp has stopped. There is a small bit of activity over in hdt-java. How safe is it, in general, to use HDT in a new project? Are there alternative binary RDF serializations that have more community support?

**Comment by mielvds** [comment]
Hi @kinghuang! I would have to say: a little. I think there are some organizations that are developing it further, but for what the CPP version is concerned, it's mostly in the shadows (I mean to communicate about that soonish). The java version gets more PRs, but it's also not progressing with high pace. I come here once and a while to review and merge some things, but I'm unfortunately not in a position to develop on it. 

That said, I would say the codebase is pretty stable! It works pretty well, which is good enough for new projects. There are other binary RDF serializations, such as [RDF for apache thrift](https://jena.apache.org/documentation/io/rdf-binary.html), [RDF4J binary](https://rdf4j.org/documentation/reference/rdf4j-binary/), but they focus on faster processing, not compression. I think when it comes to compressing RDF while maintaining query capabilities, HDT is pretty unique (and awesome)

**Comment by kinghuang** [comment]
Ah, it's unfortunate that HDT doesn't have more traction! It slots in really easily for Python based apps using rdflib, and the compression is a plus for me. I'll take a look at those two other options you listed, too. Thanks!
