### ISSUE TITLE
ModifiableHDT?

### ISSUE THREAD

**Issue by JanWielemaker** [rdfhdt/hdt-cpp#23]
I'm working on a SWI-Prolog interface to this library.  Read access now mostly works.  Now, I try to make it possible to create HDTs from triples available in Prolog.  I could of course first write an ntriples file but that seems a waste of resources.  I tried including `HDTFactory.hpp`, create an instance of a basicModifiableHDT, using `HDTFactory::createDefaultModifiableHDT()` and call ->insert() and ->save() on that.  This creates a file, but trying to open it using `hdt2rdf` says

```
ERROR: This software cannot open this version of HDT File
```

What am I missing?

**Comment by mielvds** [comment]
This might be simply unimplemented or a support class for the standard HDT creation. What is the filesize and triple count?

**Comment by mielvds** [comment]
@JanWielemaker in the meantime, we've added fixes and versioning. Could you check whether this is still an issue?

**Comment by RubenVerborgh** [comment]
ModifiableHDT is not supported at the moment.
