### ISSUE TITLE
Replace use of deprecated ftime()

### ISSUE THREAD

**Issue by donpellegrino** [rdfhdt/hdt-cpp#251]
The ftime() function is deprecated. Calls should be changed to use a different function:

```
src/static/textindex/suftest3.test.cpp:65:3: warning: 'ftime' is deprecated [-Wdeprecated-declarations]
                ftime(t);
                ^
/usr/include/x86_64-linux-gnu/sys/timeb.h:40:19: note: 'ftime' has been explicitly marked deprecated here
  __nonnull ((1)) __attribute_deprecated__;
                  ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:251:51: note: expanded from macro '__attribute_deprecated__'
# define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                  ^
```

Note that this is a file in the hdt-cpp fork of the unmaintained libcds library. Issue #19 has identified libcds to be replaced with the sdsl-lite library. Putting the effort into replacing libcds will eliminate the class of problems of code maintenance on the old local copy of libcds.

**Comment by donpellegrino** [comment]
Code without ftime() was already in there but had been conditioned out if a `#if 1`. Removing the weird constant conditional and fixing the syntax of mytimestruct's declaration fixes the problem.

**Comment by mielvds** [comment]
So why was it commented out? There must have been a reason. AFAIK, this libcds branch has not been completed?
