### ISSUE TITLE
Code formatting / beautifier needed.

### ISSUE THREAD

**Issue by donpellegrino** [rdfhdt/hdt-cpp#257]
The formatting of the C++ code is inconsistent. This makes it difficult to read. Indents are different sizes, sometimes using tabs, sometimes spaces. In general, the codebase needs to be run through a formatter tool to ensure consistency. Something like clang-format (https://clang.llvm.org/docs/ClangFormat.html) might help.

This is usually a significant change that causes havoc with revision control. Ideally, at a point when most pending pull requests are resolved, the entire codebase would be run through the formatting tool to establish a new baseline for code changes.

**Comment by mielvds** [comment]
Good suggestion! I think we can do this in de develop branch right before a new release.
