### ISSUE TITLE
OFFSET is not working in constant time

### ISSUE THREAD

**Issue by webdata** [rdfhdt/hdt-cpp#28]
@momo54 reported that although he was expecting nearly constant time in OFFSETS (using "goto" methods in [BitmapTriplesIterators.cpp](https://github.com/rdfhdt/hdt-cpp/blob/master/hdt-lib/src/triples/BitmapTriplesIterators.cpp)), he practically observed large delays using Linked Data Fragments+HDT with particular\* OFFSET queries: SP?o,  S?p?o, ?sPO and ?s?pO + OFFSET
- Note that ?sP?o +OFFSET cannot run in constant time with our current implementation.

**Comment by webdata** [comment]
In fact, I found that the goto in BitmapTriplesIterators was only working for ?s?p?o patterns. I fixed the [goto method](https://github.com/rdfhdt/hdt-cpp/blob/master/hdt-lib/src/triples/BitmapTriplesIterators.cpp#L250) to work in constant time for SP?o and s?p?o queries (commit 50005547a723f497c32237939b677467699beee6). Now LDF should "paginate" in constant time for SP?o and s?p?o offsets, which could be a difference for large datasets with many results.

I think ?sPO and ?s?pO + offset was already properly implemented in the library, but @momo54 @RubenVerborgh  @mielvds  maybe you can have a look and check in LDF. 
  
Cheers,
Javier

**Comment by mielvds** [comment]
thanks, great. Will do and report back.

**Comment by rubensworks** [comment]
I think @RubenVerborgh's HDT-Node has not been updated yet to use the latest HDT code.
The following code can explain the non-constant time offsets: https://github.com/RubenVerborgh/HDT-Node/blob/master/lib/HdtDocument.cc#L142-L146

**Comment by mielvds** [comment]
That code is on the TripleID iterator level, should automatically include the fixes. Or do you mean the submodule has to be updated, which should be the case.

**Comment by RubenVerborgh** [comment]
@mielvds I indeed need to update HDT-Node with the latest version of the submodule. @rubensworks there is indeed a fallback to linear behavior if a jump is not possible for any reason.

**Comment by RubenVerborgh** [comment]
Node.js package updated and released as [v1.2.6](https://github.com/RubenVerborgh/HDT-Node/releases/tag/v1.2.6).
