### ISSUE TITLE
Alter Makefile to make code position-independent?

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#38]
Compilation in SWI-Prolog's HDT package requires me to add `-fPIC` to
the `FLAGS` variable (on lines 14 and 16).  I'm not sure whether this
is a bug or not.  According to someone on SO PIC stands for:

    > Position Independent Code means that the generated machine code
    > is not dependent on being located at a specific address in order
    > to work.

My editor also complains about a spurious horizontal tab character on
line 111.  This may be removed if only for aesthetic reasons.

**Comment by wouterbeek** [comment]
Duplicate of #22 .

**Comment by bendiken** [comment]
Not necessarily a duplicate as such, but yes, that ticket subsumes this as well.
