### ISSUE TITLE
Merge HDT files or update HDT with rdf

### ISSUE THREAD

**Issue by jjkoehorst** [rdfhdt/hdt-cpp#39]
Is it possible or is it in the scope of HDT to merge multiple HDT files or update a HDT file with another rdf file?

This would be great for analysis pipelines that generate new RDF triples based on the content of the input rdf/hdt files.

**Comment by webdata** [comment]
Yes, it is possible to merge a turtle file in an existing HDT, or two HDT into another HDT. However, given our intensive use of static compact structures, this is "almost"  as costly as exporting and
generate it again.

Let us have a look and come back to you asap.

**Comment by jjkoehorst** [comment]
Thank you for your response. Yes I would have assumed this would be relatively costly but given the fact that we currently perform a 

Turtle > Memory > Update > Turtle ... > Next application ... etc...

It should speed up the process as you would not really have to load the HDT file at the start

**Comment by webdata** [comment]
I have fixed an existing merge tool in the tests folder: [mergeHDT.cpp](https://github.com/rdfhdt/hdt-cpp/blob/master/hdt-lib/tests/mergeHDT.cpp)

Please test it  and let us know if this helps. Next we can do something similar to work on several RDF files (instead of existing HDTs)

* Compilation: "make tests".
* Run: mergeHDT [options] <hdt output file> [<hdt intput file>]+
       E.g.: ./tests/mergeHDT out.hdt data/test.hdt data/test2.hdt

**Comment by jjkoehorst** [comment]
I performed several tests and it works really good. Thanks!

Not to be annoying but are you also planning a java version of this function? Or should I then convert to RDF and reload the files?

**Comment by ahmad88me** [comment]
# MacOS
Compiling with `make tests` didn't generate the merge binary. So I compiled it (after installing the hdt library) as follows:
```
cd libhdt/tests
g++ mergeHDT.cpp -lhdt
```
Then it can be used as follows:
```
./a.out
```
Note: This has been tested on MacOS

# Linux (ubuntu)
The same command gave the following error: (solution is included below) 
```In file included from /usr/local/include/RDF.hpp:35:0,
                 from /usr/local/include/HDT.hpp:35,
                 from mergeHDT.cpp:30:
/usr/local/include/SingleTriple.hpp: In member function ‘int hdt::TripleID::compare(hdt::TripleID&)’:
/usr/local/include/SingleTriple.hpp:201:9: error: ‘int64_t’ was not declared in this scope
         int64_t result = (int64_t)(this->subject - other.subject);
         ^
/usr/local/include/SingleTriple.hpp:203:6: error: ‘result’ was not declared in this scope
   if(result==0) {
```

This is solved by using the argument ` -std=c++14`. 
```
g++ -std=c++14  mergeHDT.cpp -o mergeHDT -lhdt
```
