### ISSUE TITLE
Implement proper branch management

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfhdt/hdt-cpp#44]
Bugs such as https://github.com/LinkedDataFragments/Client.js/issues/26#issuecomment-264713082 occur because people use the latest master as opposed to the latest release.

**Proposal A** (vote with 👍 )
- `develop` becomes the branch were development happens
- `master` always points to the latest release (which we tag)

**Proposal B** (vote with 😄 )
- `stable` becomes the default branch

**Comment by mielvds** [comment]
Wasn't Proposal A not already the case?

**Comment by mielvds** [comment]
Ah nevermind, I got confused with repos

**Comment by RubenVerborgh** [comment]
Given the 4 votes, this is settled. To be implemented starting with the next release.

**Comment by mielvds** [comment]
I've created a Milestone for the next release to organize things. We should have this biannual.

**Comment by mielvds** [comment]
@RubenVerborgh you feel like making this change?

**Comment by RubenVerborgh** [comment]
Done. Development on `develop` from now on; next commit on master is release.
