### ISSUE TITLE
determine node type from id

### ISSUE THREAD

**Issue by vandenoever** [rdfhdt/hdt-cpp#51]
A subject can be a blank node or an iri. An object can be a blank node, an iri or a literal. A TripleID contains `unsigned int` for subject, object and predicate.

Is there a cheap way to determine the type of the node without retrieving the string value?

The nodes are sorted in the dictionary. Blank nodes start with '_', literals start with '"' and IRIs start with '<'. So by knowing the number of blank nodes, IRIs and literals in the dictionary, it is possible to determine the node type from the id.

**Comment by RubenVerborgh** [comment]
My suggestion: perform two binary searches on the nodes to find out the position of the first literal and first IRI. Then use the resulting ids as markers, so you can find out the type by numerical comparison.
