### ISSUE TITLE
rdf2hdt issues

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#53]
There are a few issues with the `rdf2hdt` command:

- It does not always print to stdout (using `rdf2hdt file.hdt -`).
- The built-in N-Triples serializer works, but when the Raptor serializer is included it does not.
- Do we want raptor as a serializer anyway? (considering that the parser lib was changed to serd #31)

**Comment by RubenVerborgh** [comment]
Side note: Serd replaced the default N-Triples parser; raptor might still be useful for XML (not for me though 😊). But if the internal N-Triples writer is good, raptor can go.

**Comment by LaurensRietveld** [comment]
The internal ntriples writer works fine for me so far. I'll use it a bit more, and if there are no problems I'll put in a PR to remove raptor

**Comment by LaurensRietveld** [comment]
Just to verify: you're talking about raptor still being useful as parser, but not as serializer right? I.e., if the internal ntriple serializer is sufficient, we're going to remove the raptor dep and only support ntriple as serialization output

**Comment by RubenVerborgh** [comment]
Indeed. However, we should double-check escaping and special characters (because this is where the built-in parser was horribly broken).

**Comment by drobilla** [comment]
I implemented a Serd serializer in https://github.com/rdfhdt/hdt-cpp/pull/75

This should fix any escaping/etc issues that might be hanging around and also support abbreviated Turtle output with similar performance (Serd does this in constant space).

I have no stance on dropping the internal NTriples serializer if you don't mind a mandatory dependency on Serd, though less code is always good.  Dropping Raptor entirely would mean the loss of XML support, though, since Serd does not and will never support XML.

**Comment by RubenVerborgh** [comment]
I think Serd is the way forward. We should drop all Raptor support for everything besides XML, so we don't have to maintain two versions.

@drobilla Could you do an official release of Serd 0.27.1, which is needed to compile this?

**Comment by RubenVerborgh** [comment]
Ported this issue to #76 and #77.

**Comment by drobilla** [comment]
That'd be 0.28.0 (I do the even number stable release thing).

Sure, I can do so shortly, but unfortunately just added new API for this once again so I need to go through some things before releasing and can't do it this instant.  Both reading and writings in hdt-cpp works well now though without any hacks, so I think it's fine.  I'll release this week some time.

**Comment by RubenVerborgh** [comment]
Perfect, then we can release a new hdt-cpp when 0.28.0 is available.

**Comment by drobilla** [comment]
http://drobilla.net/2017/07/21/serd-0-28-0.html
