### ISSUE TITLE
hdtSearch improperly handles spaces in input literals

### ISSUE THREAD

**Issue by osma** [rdfhdt/hdt-cpp#55]
I noticed problems with both hdtSearch (cpp) and hdtSearch.sh (java). Both apparently give incorrect results in some cases when looking for a specific literal value. I will report the Java results in a separate issue for hdt-java.

My test dataset is this NT file with only 3 triples:
```
<http://example.org/000046085> <http://schema.org/name> "Raamattu" .
<http://example.org/000146854> <http://schema.org/name> "Ajan lyhyt historia" .
<http://example.org/000019643> <http://schema.org/name> "Seitsemän veljestä" .
```

I converted it to HDT using the cpp version of rdf2hdt. Then I query it for the literal values using hdtSearch:

```
$ rdf2hdt hdt-test.nt hdt-test.hdt
HDT Successfully generated.                                                    
Total processing time: Clock(801 us)  User()  System()

$ hdtSearch hdt-test.hdt
Predicate Bitmap in 34 usp: 0 % / 14.86 %                            
Count predicates in 16 userences: 0 % / 16.075 %                      
Count Objects in 9 us Max was: 1: 0 % / 34.3 %                      
Bitmap in 7 usx bitmap: 0 % / 45.64 %                      
Bitmap bits: 3 Ones: 3
Object references in 13 usces: 0 % / 48.475 %                      
Sort lists in 8 usblists: 0 % / 68.32 %                      
Index generated in 136 us
>> ? ? "Raamattu"                                 %                      
http://example.org/000046085 http://schema.org/name "Raamattu"
1 results in 40 us
>> ? ? "Ajan lyhyt historia"
0 results in 5 us
>> ? ? "Seitsemän veljestä"
0 results in 6 us
```

As you can see from the above output, the first query (for "Raamattu") gives the correct result, but the two subsequent ones give zero results even though they should match one triple in the data.

I'm not sure whether the problem is in the HDT generation, index file generation, or querying. However, I did try generating the index with `hdtSearch.sh` from hdt-java instead. It didn't make a difference to the results.

**Comment by RubenVerborgh** [comment]
From previous experience, I would say the problem is in the hdtSearch input parser. So the HDT file is likely fine (as can be confirmed with `hdt2rdf` and when reading it with [HDT-Node](https://github.com/RubenVerborgh/HDT-Node)), but hdtSearch somehow does not deal well with non-ASCII. I suspect an encoding problem.

**Comment by osma** [comment]
Note that the second query only has ASCII characters, and it also fails.

**Comment by RubenVerborgh** [comment]
Sorry, missed that. Might be even more problematic then. Maybe an ordering issue.

**Comment by osma** [comment]
(in case anyone wonders, these are Finnish book titles: "Raamattu" is the Bible, "Ajan lyhyt historia" is a translation of "A brief history of time" by Stephen Hawking, and "Seitsemän veljestä" is an original work by Aleksis Kivi, translated to English as "Seven brothers")

**Comment by RubenVerborgh** [comment]
Generated a 3-triple HDT in pure ASCII; problem still occurs. It's not an encoding bug.

**Comment by osma** [comment]
I just did basically the same, by omitting the third triple, and yes, the problem still occurs.

**Comment by webdata** [comment]
Hi, I think there is a problem in parsing the space in the query, I think I have it solved locally, let me check

**Comment by RubenVerborgh** [comment]
Indeed, found the same; it works without spaces.

**Comment by osma** [comment]
Yes, when you remove the spaces from the data and the query, even the third case with the non-ASCII characters starts working.

**Comment by webdata** [comment]
@osma Can you fetch the brach develop and try? I think it should be working now

**Comment by osma** [comment]
@webdata Confirmed, it works now with the `develop` branch. Thanks!

**Comment by webdata** [comment]
Perfect, I will fix the java version as well

**Comment by osma** [comment]
@webdata Excellent (re java), that's actually more important to me since I care more about SPARQL, not so much the command line query utilities.
