### ISSUE TITLE
Parsing of blank nodes

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#59]
Parsing of blank nodes in the object position returns invalid terms. To reproduce:

`echo "<http://sub> <http://pred> _:b0." > test.nt &&  ./tools/rdf2hdt test.nt test.hdt && ./tools/hdtSearch -q '? ? ?' test.hdt 2>/dev/null`

HDT with the rapper parser returns `http://sub http://pred b0.` (notice the missing `_:`)
HDT with the serdi parser returns `http://sub http://pred _:b0.` (notice the trailing dot, which should not be there)

As a result, when you export this triple to RDF using `hdt2rdf`, you'll get invalid ntriples[1]

I'm confused about this issue though. Running `echo "<http://sub> <http://pred> _:b0." | serdi -` returns valid ntriples, i.e. serdi seems to parse/serialize this correctly.
But when I log the SerdNode value in the HDT serializer (https://github.com/rdfhdt/hdt-cpp/blob/develop/hdt-lib/src/rdf/RDFParserSerd.cpp#L18) I _do_ get the dot as part of the bnode value.

Some help is appreciated ;)

[1] 
serdi: `<http://sub> <http://pred> _:b0. .`
rapper: `<http://sub> <http://pred> <b0.> .`

**Comment by RubenVerborgh** [comment]
Fixed by #69 for Serd.
