### ISSUE TITLE
Cannot save Index if the HDT is not saved

### ISSUE THREAD

**Issue by CristianCantoro** [rdfhdt/hdt-cpp#6]
Using the `rdf2hdt` tool with the `-i` option I keep getting this warning/notice (it is not presented as an error). This message is quite confusing, how should the program be called to generate the HDT index?

Thanks,

C

**Comment by bendiken** [comment]
Confirmed that this still happens with the current HEAD, and is indeed rather confusing. Steps to reproduce with a tiny N-Triples file:

    $ wget http://ar.to/foaf.nt
    $ tools/rdf2hdt -i foaf.nt foaf.hdt
    HDT Successfully generated.                                                    
    Total processing time: Clock(1 ms 96 us)  User(1 ms 21 us)  System()
    Predicate Bitmap in 25 usp: 0 % / 5.4 %                             
    Count predicates in 17 userences: 0 % / 6.75 %                      
    Count Objects in 12 us Max was: 2 0 % / 27 %                      
    Bitmap in 12 us bitmap: 0 % / 39.6 %                      
    Bitmap bits: 20 Ones: 17
    Object references in 26 usces: 0 % / 42.75 %                      
    Sort lists in 14 uslists: 0 % / 64.8 %                      
    Index generated in 181 us
    Cannot save Index if the HDT is not saved

**Comment by bendiken** [comment]
Figured out that a workaround is execute, which automatically creates an index file as needed:

    $ tools/hdtSearch foaf.hdt
    Predicate Bitmap in 34 usp: 0 % / 14.86 %                            
    Count predicates in 16 userences: 0 % / 16.075 %                      
    Count Objects in 13 us Max was: 2 0 % / 34.3 %                      
    Bitmap in 12 us bitmap: 0 % / 45.64 %                      
    Bitmap bits: 20 Ones: 17
    Object references in 32 usces: 0 % / 48.475 %                      
    Sort lists in 14 uslists: 0 % / 68.32 %                      
    Index generated in 231 us

    $ ls -l foaf.hdt*
    -rw-rw-r-- 1 arto arto 2499 Nov 10 15:11 foaf.hdt
    -rw-rw-r-- 1 arto arto  135 Nov 10 15:16 foaf.hdt.index

**Comment by RubenVerborgh** [comment]
We have seen such issues also, and always do it in two steps:
```
rdf2hdt -i foaf.nt foaf.hdt
hdtSearch -q 0 foaf.hdt
```

The `-q 0` (dummy query) is to avoid hdtSearch goes in interactive mode.

**Comment by bendiken** [comment]
@RubenVerborgh :+1: for that noninteractive `hdtSearch` invocation, comes handy.

**Comment by bendiken** [comment]
Have to look at how to fix this problem soonish, it's causing headaches here at the [SWAT4LS hackathon](http://www.swat4ls.org/workshops/cambridge2015/programme/hackathon/) where we're working on having bioinformatics people convert their datasets to HDT...

**Comment by RubenVerborgh** [comment]
@bendiken I don't know if it's related, but many datasets contain invalid Turtle (and the HDT utility does not give correct error messages for that). I always run datasets through `serdi` before trying to convert.

**Comment by mielvds** [comment]
Does anyone have a proposed fix for this? Can we still include it in the next milestone?

**Comment by RubenVerborgh** [comment]
At the moment, this is broken in a different way:

```bash
$ tools/rdf2hdt -i foaf.nt foaf.hdt
ERROR: You must supply an input and output
```

**Comment by samuell** [comment]
Quoting @RubenVerborgh:

> ```
> rdf2hdt -i foaf.nt foaf.hdt
> hdtSearch -q 0 foaf.hdt
>```

Is that first step significant in this case?

I'm running into problems after doing only the second step (on a huge dataset), so thus was wondering.

**Comment by webdata** [comment]
Hi, I have fixed the -i issue in develop, https://github.com/rdfhdt/hdt-cpp/commit/18cf4f2a1141d82ad96748a312789c66af64f3c0 

This should be enough to create your index: 

> rdf2hdt -i foaf.nt foaf.hdt
