### ISSUE TITLE
getSuggestions without max_count argument

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#65]
Function `getSuggestions` is very nice since it implements the following two common use cases:
  1. Auto-completion for typing IRIs and literals
  2. IRI namespace matching

Currently a maximum size must be given to the function, but this maximum is not always known beforehand.  For example, if you want to find all DOI IRIs (use case category 2), there are over 4M matches for prefix `http://dx.doi.org/` in `LOD-a-lot`.

Would it be possible to return the list of suggestions as an iterator of lazy list of arbitrary size?

**Comment by webdata** [comment]
I have implemented an iterator for getSuggestions in [develop](https://github.com/rdfhdt/hdt-cpp/tree/develop), commit https://github.com/rdfhdt/hdt-cpp/commit/d7e93d1dbd3fe647c20524ccf1e6166f8930a867

See an example of use in: [tests/getSuggestions](https://github.com/rdfhdt/hdt-cpp/blob/develop/hdt-lib/tests/getSuggestions.cpp)

Let me know if this solves this issue.
