### ISSUE TITLE
Compilation problem in develop

### ISSUE THREAD

**Issue by webdata** [rdfhdt/hdt-cpp#66]
Introduced in:
https://github.com/rdfhdt/hdt-cpp/commit/686e25d8022d1cf7d0585e8f9f8662e7fee6b8ce

**Comment by RubenVerborgh** [comment]
Why is this in develop already :-(
Should have remained in long-dict-id until the build was fixed.

**Comment by RubenVerborgh** [comment]
Related: #63 / https://github.com/rdfhdt/hdt-cpp/issues/63#issuecomment-305115012

**Comment by webdata** [comment]
No no this compilation problem is not related to the long-dict-id, and long-dict-id has not been merged into develop yet :) Sure, let's fix this problem first

**Comment by RubenVerborgh** [comment]
Indeed, I see!

Hmm, after the failing commit 686e25d8022d1cf7d0585e8f9f8662e7fee6b8ce, nothing else should have been done on develop except for fixing the build again. Travis detected the build failure. @MarioAriasGa Do you receive these failure notifications by mail?

**Comment by MarioAriasGa** [comment]
Sorry, I don't receive travis emails, can you please add me?

I will look into this issue. I think it is probably due to the unordered_map being so different between compilers.

**Comment by RubenVerborgh** [comment]
@MarioAriasGa I think you just need to register at https://travis-ci.org/, and the rest happens automatically since this project is already on Travis CI.

**Comment by RubenVerborgh** [comment]
This issue should be fixed with high priority; we currently cannot build other features on top of `develop`.

@MarioAriasGa Could you give an estimate for a fix? Otherwise, I'll need to roll back `develop` to the last working version 2ca11fe0b448495f241cd85a06c170b4ae36b3fd and place the current work in progress in a separate branch.

**Comment by RubenVerborgh** [comment]
I reset `develop` to the last working commit 7a067abde7be84a3ba4e74294bacb939b63767c7 and pushed the broken branch to `develop-broken`.
