### ISSUE TITLE
Cannot create HDT file when numbers appear in IRI schema

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#68]
I'm unable to create an HDT file for the following N-Triples content:

```nt
<a:b> <a:b> <a2:b>
```
The problem is caused by the `2`, which is allowed to appear in IRI schema components, but gives the following error:

```
syntax does not support relative IRIs
Catch exception load: Error parsing input.
```

The `serdi` command-line tool parse this content correctly.

I'm using Serd 0.26.0 and HDT commit d4b5244a7d3f95d03ac8827c6418508c69289fb0

**Comment by RubenVerborgh** [comment]
This happens with `-f turtle`?

**Comment by wouterbeek** [comment]
@RubenVerborgh Ha, `serdi -i ntriples <FILE>` gives the error, but `serdi -i turtle <FILE>` does not.

Strange, because the triple is valid Turtle/TriG/N-Triples/N-Quads, so I did not expect the grammar would matter.  Closing the issue here and opening it at the Serd project...

**Comment by RubenVerborgh** [comment]
No no, not SERD! `-f ntriples` triggers different (buggy) parser, I think.

**Comment by RubenVerborgh** [comment]
Ah no, still SERD. Go ahead.

**Comment by wouterbeek** [comment]
FYI https://github.com/drobilla/serd/issues/1

**Comment by RubenVerborgh** [comment]
@wouterbeek Hmm, strangely low issue number. Seems that he takes issues here: http://dev.drobilla.net/newticket?component=Serd
