### ISSUE TITLE
Remove Raptor support for everything but XML

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfhdt/hdt-cpp#77]
Serd is now supported for both parsing and serializing. We should probably not maintain two parsers, and only keep Raptor around for XML.

Discussed in #53.

**Comment by RubenVerborgh** [comment]
Let's wait for #81 to fix this.

**Comment by LaurensRietveld** [comment]
I propose to remove the serialization support for XML as well. That way we only have to support the serd serializer

**Comment by RubenVerborgh** [comment]
Fine with we, but we do lose functionality though then (whereas we don't with removing Raptor). That said, seem even better to leave XML conversion to external tools.

**Comment by LaurensRietveld** [comment]
Well, tbh I actually meant to remove raptor support for rdf serialization only, and keep it for the parsing stuff. But removing raptor completely is fine with me as well. Saves us one dependency to maintain, and rdf/xml is such a legacy format..

**Comment by LaurensRietveld** [comment]
Can we say there is a consensus on removing raptor completely? (i.e. disgarding XML as input and output format) If so, then we might prepare a PR for this

**Comment by drd-ableton** [comment]
As long as everyone promises to never request XML support in serd, because no. :)

**Comment by webdata** [comment]
Hi! I was talking to someone in SEMANTiCS from a company that integrates different data sources, and they are still using RDF/XML. Well, I am also fine with removing raptor, we can label the old raptor code somehow such that anyone can hack a bit to put it back if really needed.

**Comment by wouterbeek** [comment]
@webdata If this feature is valuable to them, this company may be able to contribute the maintenance of the Raptor option to the hdt-cpp project?  That would be a win-win.

**Comment by RubenVerborgh** [comment]
Nah, we should just support piping from STDIN (#25) and then they should pipe from `rapper`.

**Comment by wouterbeek** [comment]
@RubenVerborgh Thanks for the pointer, but this pull request has remained unmerged for well over a year.  Maybe the aforementioned company can put their weight behind rebasing and merging this pull request?

**Comment by RubenVerborgh** [comment]
I'm sure that @rubensworks is happy to take it up again. I propose to continue with the removal of Raptor.

**Comment by rubensworks** [comment]
@RubenVerborgh I would have time to look into rebasing/rewriting #25. I'm just wondering if it is still necessary, as @MarioAriasGa [has pointed out](https://github.com/rdfhdt/hdt-cpp/issues/47#issuecomment-293081709) that piping can already be done on Mac and Linux.

Furthermore, #25 _only_  adds a new method for streaming triples into `BasicHDT`, STDIN streaming would have to be implemented on top of that.

**Comment by LaurensRietveld** [comment]
Raptor is removed as dep in the develop branch (see #98), so I'll just close this issue. The issue with not being able to pipe th `rdf2hdt` still seems to be unresolved, but let's discuss that in #47
