### ISSUE TITLE
Question about .gz parsing

### ISSUE THREAD

**Issue by kurzum** [rdfhdt/hdt-cpp#82]
Dear all,
I have a short question. I checked that libz is installed and I have an ntriples file called core.nt.gz

Will the program automatically recognize that the file is zipped, if I call 
```./rdf2hdt core.nt.gz core.hdt```

because I receive a lot of parser errors. Maybe I am missing an option.
I also tried `-f ntriples` 

If I unzip the file first, it works.

**Comment by LaurensRietveld** [comment]
Did you try the develop branch as well? If you compile that one (with serd included), it should work fine. See this related pr: #61

**Comment by kurzum** [comment]
./tools/rdf2hdt ../../data/commons/core.gz ../../data/commons/core.hdt

**Comment by LaurensRietveld** [comment]
Which branch did you compile? The master or the develop branch?

**Comment by kurzum** [comment]
develop

**Comment by LaurensRietveld** [comment]
And you're still getting errors? If you're parsing ntriples, then you onlyneed serd.

**Comment by kurzum** [comment]
```
git branch
* develop
  master
```
```
head Makefile
OS := $(shell uname)

LIBCDSPATH = ../libcds-v1.0.12

# Uncomment here to enable optional dependencies
RAPTOR_SUPPORT=true
#KYOTO_SUPPORT=true
LIBZ_SUPPORT=true
SERD_SUPPORT=true
```
`make` ran without problems, but with a small warning

**Comment by kurzum** [comment]
No errors, but no stdout output as well. 
Ok, let me wait a bit. For DBpedia we intend to run this weekly and the files are quite large (this is gz size):
```
21G	commons
5,1G	de
15G	en
4G	fr
30G	freebase
3,3G	ru
9,4G	viaf
16G	wikidata
```
We probably need to process these within two days or so. Do you think this is realistic?

**Comment by kurzum** [comment]
```
root@Ubuntu-1704-zesty-64-minimal ~/hdt-cpp/hdt-lib # ./tools/rdf2hdt ../../data/commons/core.gz ../../data/commons/core.hdt

<nothing here>

```
This is my screen at the moment, in the master branch there was some output that counted the triples. Anyhow, I will just give it some time.

**Comment by LaurensRietveld** [comment]
you mean the process doesn't exit, but just returns no output? If you want output you can specify the `-v` flag for verbosity, or the `-p` flag for progress.

About the files: (assuming they are gzipped): if you create an hdt for each file, and run these processes independently, you should have them within a day (depending on your hardware of course)

**Comment by kurzum** [comment]
Thanks, these are good Tipps. 
I should have run - h to see the new options 

So I can batch the 120 files in twelve processes, one for each core and deactivate raptor. 

Is there the danger of getting an out of memory error like in Java?  235gb ram was not enough for 20gb gz ntriples. 

One more thing. The triples in the gz files are not sorted. Is this a requirement?

**Comment by LaurensRietveld** [comment]
Sorted triples aren't a requirement. About the mem usage : not sure about the mem requirement  differences between Java and the c++ version.  Needing that much mem for a 20gb zipped files sounds like a lot, but it depends on the structure of the graph in the file as well of course.
