### ISSUE TITLE
New hdt version

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#83]
What about merging develop to master? I've been using the latest develop branch intensively and it seems there are no issues that should stop it from becoming the next version. 
If we do the merge soon, we can use the develop branch to start properly testing the new compilation procedure (#81)

**Comment by RubenVerborgh** [comment]
Agree, let's do exactly that: merge to master and start testing #81.
However, I'd also propose that merging to master is accompanied by a new version number, and that we have explicit version commit from now on.

Given the breaking changes, I propose to release v2.0.0 of the library. The supported HDT format will still be v1.0.0. And, if I'm not mistaken, the index file format has not changed, so we do not need a version bump there either.

**Comment by RubenVerborgh** [comment]
Hmm, in the milestones list, I see that we were working toward https://github.com/rdfhdt/hdt-cpp/milestone/1. However, if we follow semver, we need to make this a major release, since the API is not backward compatible.

We might, however, choose to _not_ use semver, but instead have the major version number reflect the supported HDT format.

**Comment by LaurensRietveld** [comment]
I like the idea of having the major version number reflect the HDT format. I guess the next major release would then be when the long-dict-id branch is merged. 
So, we'd have a new 1.2 release, and move the remaining milestone issues to the following release?

**Comment by RubenVerborgh** [comment]
I'd just like to have a look at #77, or in the very least ensure that the default parser is Serdi, such that all generated HDT files are always valid. I'll take this up.

**Comment by RubenVerborgh** [comment]
On second thoughts, let's tackle #77 when the new build system is in place.

I'll take care of the 1.2.0 release, but I just want to ensure that the README is correct and that no more broken HDT files can be generated.

**Comment by RubenVerborgh** [comment]
Released 1.2.0 in cd79e497b01b8cb0db4d4b09303ffea04be61db9.

**Comment by RubenVerborgh** [comment]
Had to retract 1.2.0 😞  Querying is broken (#84).

**Comment by LaurensRietveld** [comment]
Ai, that's too bad. Good catch though

**Comment by RubenVerborgh** [comment]
Released a working 1.2.0: https://github.com/rdfhdt/hdt-cpp/releases/tag/v1.2.0
