### ISSUE TITLE
rdf2hdt with 2bn triples gives "out of memory" on 256GB RAM

### ISSUE THREAD

**Issue by samuell** [rdfhdt/hdt-cpp#90]
I have a file with some 2 billion triples (2012963722 to be exact), according to a pretty simple schema, that takes up 6,5GB as gzipped N3.

When running hdt2rdf v1.1.2 (compiled from commit ad9a5d4abb00e8b1d8382fe194ad80dc5c0c5ce3) on a node with 256GB RAM, it runs out of memory though. Any hints of other approaches to take, or any plans for making rdf2hdt use less memory?

Version:

```bash
$ rdf2hdt -V
v1.1.2
```

Command executed (via SLURM script):

```bash
rdf2hdt -f n3 <(zcat dat/cplogd_dataset.n3.gz) dat/cplogd_dataset.hdt
```

Output:

```bash
RDF format: n3
Parser message: => out of dynamic memory in turtle_lexer__scan_bytes() at line 1
/var/spool/slurmd/job1021359/slurm_script: line 7: 15901 Segmentation fault      (core dumped) rdf2hdt -f n3 <(zcat dat/cplogd_dataset.n3.gz) dat/cplogd_dataset.hdt
```

OS: 

```bash
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

RAM: 256GB

**Comment by wouterbeek** [comment]
HDT generation does take a lot of memory!  @LaurensRietveld  recently created an HDT file with more than 1B triples, maybe he can report on the memory that was used in that case, for some rudimentary comparison.

Also, 2 billion is a dangerous number...  To be more specific, 2,147,483,647 is a dangerous number.  Not only is it a prime number, but it is also the largest address that can be represented with 32 bits.  You may or may not run into this limit with your dataset.

64 bit support was added recently by @webdata, but it's experimental and currently in the `long-dict-id` branch.

**Comment by LaurensRietveld** [comment]
If I recall correctly I used ~170GB of ram for a file with ~1.6 billion triples. I did this using the develop branch btw. There might be some optimization there such as this one: #80

**Comment by samuell** [comment]
@wouterbeek Thanks for the info - good to know that problems at least might be expected.
@LaurensRietveld Ah, that's good to know - should probably give the develop branch a try then.

**Comment by samuell** [comment]
Tried re-compiling the tools now with the develop branch - same problem though. Runs out of memory within a few minutes, on the 256GB RAM node.

**Comment by wouterbeek** [comment]
The "within a few minutes" part seems suspicious to me...  Do others here agree?

**Comment by webdata** [comment]
@samuell is the data available such that we can try to reproduce the error?

**Comment by samuell** [comment]
@webdata The gzipped input data file is now available [here](https://export.uppmax.uu.se/b2013262/cplogd_dataset.n3.gz). Cheers

**Comment by wouterbeek** [comment]
@samuell In the file you link to namespace `cplogd` does not seem to be defined?  This means that `cplogd:something` is parsed as an absolute IRI of scheme `cplogd`.  This is not the cause of your problem, but maybe something to fix anyway.

**Comment by samuell** [comment]
@wouterbeek Oh sorry about that! I was sure I had fixed that already, but must have mixed up some files. Thanks for the heads up - I'll definitely try to see if fixing this changes anything! // Cheers

**Comment by wouterbeek** [comment]
@samuell Let me know when you have a link to the fixed file.  Based on the currently shared link it is not possible to create an HDT file since Serd throws an exception because of the missing namespace declaration immediately.

(My earlier remark on parsing `cplogd:something` as an IRI is incorrect, since this will only work when the IRI is enclosed in angle brackets like `<cplogd:something>`.)

**Comment by LaurensRietveld** [comment]
@samuell from your error message (that includes a reference to [this file](https://github.com/dajobe/raptor/blob/0a196219b3b4873eb882f01a374f8356061c30af/src/turtle_parser.y#L1382)) I guess you've compiled rdfhdt with raptor as serializer. It's worth trying it with serd instead

**Comment by samuell** [comment]
@wouterbeek Absolutely, will try to fix in the afternoon.
@LaurensRietveld Ah, good point! Well, I think I left both activated in the makefile, so not sure which one is actually used in the end then, but will definitely try disabling raptor and see what I get.

**Comment by samuell** [comment]
@wouterbeek [The file](https://export.uppmax.uu.se/snic2017-7-89/cplogd_dataset.n3.gz) is updated with a fixed cplogd prefix now. Again, so sorry about this.

Will go ahead and try compiling/running without raptor now.

**Comment by wouterbeek** [comment]
@samuell I'm not able to download the file, since I receive an HTTP 403 status code (see the cURL output below).

```
$ curl -vL https://export.uppmax.uu.se/snic2017-7-89/cplogd_dataset.n3.gz
> GET /snic2017-7-89/cplogd_dataset.n3.gz HTTP/1.1
> Host: export.uppmax.uu.se
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Date: Tue, 19 Sep 2017 13:52:34 GMT
< Server: Apache/2.4.6 (CentOS)
< Content-Length: 236
< Content-Type: text/html; charset=iso-8859-1
```

**Comment by samuell** [comment]
@wouterbeek Ouch, fixed link [here](https://export.uppmax.uu.se/b2013262/cplogd_dataset.n3.gz)!

**Comment by samuell** [comment]
Btw, running now without raptor, only with serd ... looks very much more promising! Only taking 15GB RAM now after running for 20 minutes!

**Comment by samuell** [comment]
@wouterbeek @LaurensRietveld Managed to finish the conversion now, by using only serd! Total RAM usage seem to have peaked at around 114.4 GB RAM (according to logging scripts run every 5 minuts, so +- something), so minus some 2GB RAM for other processes it should have been around 112GB for rdfhdt.

I did compile the develop branch, at commit 7b92caa5eba0c2618318116ef55fb6a85fbc5fb5 with the following (perhaps pretty system-specific, for CentOS 7 and the [UPPMAX Rackham cluster](uppmax.uu.se/resources/systems/the-rackham-cluster/)) changes to the Makefile:

```diff
diff --git a/hdt-lib/Makefile b/hdt-lib/Makefile
index 42ac965..173efa8 100644
--- a/hdt-lib/Makefile
+++ b/hdt-lib/Makefile
@@ -3,7 +3,7 @@ OS := $(shell uname)
 LIBCDSPATH = ../libcds-v1.0.12
 
 # Uncomment here to enable optional dependencies
-RAPTOR_SUPPORT=true
+#RAPTOR_SUPPORT=true
 #KYOTO_SUPPORT=true
 LIBZ_SUPPORT=true
 SERD_SUPPORT=true
@@ -12,21 +12,21 @@ CPP=g++
 
 OFLAGS=-O3
 
-FLAGS=$(OFLAGS) -Wno-deprecated -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-unknown-warning-option -std=c++0x
+FLAGS=$(OFLAGS) -Wno-deprecated -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-unknown-warning-option -std=c++0x -mavx2 -mfma4 -march=broadwell
 
 ifeq ($(CPP), g++)
 FLAGS+=-Wno-unused-but-set-variable
 endif
 
 INCLUDES=-I $(LIBCDSPATH)/includes/ -I /usr/local/include -I ./include -I /opt/local/include -I /usr/include
-LDFLAGS=
+LDFLAGS=-Lusr/lib64 -Lserd-0/build
 DOXYGEN=doxygen
 DEFINES= -DHAVE_CDS
 LIB=$(LIBCDSPATH)/lib/libcds.a -L/usr/local/lib -lstdc++
 
 ifeq ($(RAPTOR_SUPPORT), true)
 DEFINES:=$(DEFINES) -DHAVE_RAPTOR
-LIB:=$(LIB) -lraptor2
+LIB:=$(LIB) -lraptor2 -lyajl
 endif
 
 ifeq ($(KYOTO_SUPPORT), true)
```

**Comment by wouterbeek** [comment]
@samuell Good that the problem is solved now!  WRT your changes to the Makefile, there is [a pull request](https://github.com/rdfhdt/hdt-cpp/pull/81) from @ptorrestr that adds autotools support to hdt-cpp.  Once that is in place it should be easier to customize the build.
