### ISSUE TITLE
Add flag / option to only output data and no progress information?

### ISSUE THREAD

**Issue by samuell** [rdfhdt/hdt-cpp#92]
For `hdtSearch`, could we have a flag like `--results-only` or similar, that makes it output only the requested output, and no other information like progress etc? 

I'm experimenting with building an URI resolver web service that uses `hdtSearch` in the background to find triples linked to the URI to resolve (using two queries: `"<uri> ? ?"` and `"? ? <uri>"`).

The problem is that hdtSearch outputs a lot of other information than just the triples. Surfing in on my (WIP) web service right now looks like this:

![selection_405](https://user-images.githubusercontent.com/125003/30746501-3c08934a-9faa-11e7-9c25-efa9282d6ea5.png)

I know there is the option to write to a file using the `-o` flag, but it would be nice to avoid that, since writing to file systems can sometimes slow things down, and this service is supposed to answer quickly to web requests.

**Comment by wouterbeek** [comment]
The situation was considerably improved recently by [this pull request from David](https://github.com/rdfhdt/hdt-cpp/pull/79), but I agree that the situation could be improved even further.

IMO there is no need to print to stdout at all during HDT and/or index creation, unless debug flags are explicitly set (which would typically only be the case during development of hdt-cpp itself).

PS: I do not understand why you would run into this problem in your web service.  This output is printed only once, i.e., during HDT/index creation.  Are you creating HDT files on the fly in your web service?  Just curious.

**Comment by samuell** [comment]
@wouterbeek There is some extra output, even when the index already exists:

```bash
[samuel urisolve]$ ls -1 *.hdt*
cplogd_dataset_subset.hdt
cplogd_dataset_subset.hdt.index.v1-1
[samuel urisolve]$ hdtSearch -q "http://rdf.pharmb.io/cplogd/Compound1 ? ?" cplogd_dataset_subset.hdt
http://rdf.pharmb.io/cplogd/Compound1 http://rdf.pharmb.io/cplogd/hasLowerPoint http://rdf.pharmb.io/cplogd/C1LowerPoint0p90
http://rdf.pharmb.io/cplogd/Compound1 http://rdf.pharmb.io/cplogd/hasMidPoint http://rdf.pharmb.io/cplogd/C1MidPoint0p90
http://rdf.pharmb.io/cplogd/Compound1 http://rdf.pharmb.io/cplogd/hasUpperPoint http://rdf.pharmb.io/cplogd/C1UpperPoint0p90
http://rdf.pharmb.io/cplogd/Compound1 http://semanticscience.org/resource/CHEMINF_000376 "CC(=O)OC(CC(=O)O)C[N+](C)(C)C"
http://rdf.pharmb.io/cplogd/Compound1 http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://rdf.pharmb.io/cplogd/Compound
http://rdf.pharmb.io/cplogd/Compound1 http://www.w3.org/2002/07/owl#sameAs http://rdf.ncbi.nlm.nih.gov/pubchem/compound/1
6 results in 77 us
[samuel urisolve]$ 
```

**Comment by samuell** [comment]
Now, this was in fact *not* run from the version in develop, but from master (commit ad9a5d4abb00e8b1d8382fe194ad80dc5c0c5ce3 IIRC), so if this is fixed in develop, I guess things are all fine. 

(Had compiled the tools based off of develop on our cluster, but not on my laptop),

**Comment by samuell** [comment]
The many extra lines in the web output seem to be from the dynamically rewritten progress output shown before the results are shown. In a normal terminal, this output disappears as it is overwritten by the output (and only the last line with the stats is shown in addition to the data), but for anything that is not a terminal, it will show up as extra output.

**Comment by wouterbeek** [comment]
Ah, now I understand the issue better: you are asking whether the command-line utility that is present in the `/tools` directory can get a new flag that changes its behavior.

In the meantime, it may be easier to call the HDT search function directly, i.e., without using the scripts in `/tools`.

**Comment by samuell** [comment]
@wouterbeek Indeed, I should probably go that way. Thing is I'm writing [the web service](https://github.com/pharmbio/urisolve) in Go, and was looking for an quick way forward, without needing to interface with C++ (although that is totally doable) :)

**Comment by LaurensRietveld** [comment]
This has been improved a while ago with the introduction of the `-v` flag (verbose)
