### ISSUE TITLE
Unable to create HDT for a simple Turtle file

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#95]
I get the following error message when parsing a relatively simple Turtle file:

```sh
$ ./rdf2hdt test.ttl test.hdt
error: test.ttl:4:24: expected: ':', '<', or '_'
Catch exception load: Error parsing input.
ERROR: Error parsing input.
```

The contents of `test.ttl` are as follows (the position mentioned in the error message is right before the first integer term):

```turtle
@prefix org:    <http://example.com/ns#> .

_:a  org:employeeName   "Alice" .
_:a  org:employeeId     12345 .

_:b  org:employeeName   "Bob" .
_:b  org:employeeId     67890 .
```

The file parses correctly in both Raptor and Serd.  I'm using the latest commit from the master branch.

**Comment by mielvds** [comment]
You have to supply a type no? Else it tries to read ntriples

**Comment by wouterbeek** [comment]
@mielvds Thanks for clarifying, I now believe this to be [an issue in Serd](https://github.com/drobilla/serd/issues/9).

**Comment by drobilla** [comment]
It's loosely related to an issue in serd, but note that fixing that issue will result in exactly the same behaviour in HDT.  Ultimately this is failing to parse a Turtle file as NTriples.  Making serd _more_ strict will make this scenario happen _more_ often, not less.

In this case, it is correctly rejecting raw numeric literals.

**Comment by drobilla** [comment]
It could be avoided in most cases with a simple DWIM implementation like https://github.com/drobilla/serd/commit/f34171637b94c204971a2256849491f025862373

**Comment by RubenVerborgh** [comment]
I wouldn't sniff though, seems like N-Triples as default is sensible (performance-wise).

**Comment by drobilla** [comment]
Probably makes extremely little if any difference in this case.  Actually parsing some Turtle features it they are present can be slower, but telling serd to parse ntriples won't speed anything up significantly.

(It'd actually be a bit faster if it didn't care whatsoever, but it needs to reject things in order to pass the negative NTriples syntax tests)

**Comment by RubenVerborgh** [comment]
That would be a good argument for having Turtle as default then?

**Comment by drobilla** [comment]
I suppose, yeah.  It shouldn't result in any NTriples file failing to parse.
